queue_rules:
  - name: default
    autoqueue: true
    merge_method: squash
    queue_conditions:
      - "#changes-requested-reviews-by=0"
      - check-success=End-to-End Tests
      - check-success=Local Dev CI Gate

pull_request_rules:
  - name: automatic approval for Dependabot pull requests
    conditions:
      - author = dependabot[bot]
    actions:
      review:
        type: APPROVE

  - name: keep PRs up to date with main
    conditions:
      - -conflict
      - -draft
    actions:
      update: {}

  - name: queue PRs when CI passes
    conditions:
      - -draft
      - -conflict
    actions:
      queue:
        name: default
