# Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
# Source: ../../ambient-api-server/openapi/openapi.yaml
# Spec SHA256: 404b5671af96841f4a876b6192afc6358b4fb8e082ca2b6da499efcf3f72c781
# Generated: 2026-03-20T16:48:23Z

from __future__ import annotations

from typing import Any, Iterator, Optional, TYPE_CHECKING

from ._base import ListOptions
from .agent import Agent, AgentList

if TYPE_CHECKING:
    from .client import AmbientClient


class AgentAPI:
    def __init__(self, client: AmbientClient) -> None:
        self._client = client

    def create(self, data: dict) -> Agent:
        resp = self._client._request("POST", "/agents", json=data)
        return Agent.from_dict(resp)

    def get(self, resource_id: str) -> Agent:
        resp = self._client._request("GET", f"/agents/{resource_id}")
        return Agent.from_dict(resp)

    def list(self, opts: Optional[ListOptions] = None) -> AgentList:
        params = opts.to_params() if opts else None
        resp = self._client._request("GET", "/agents", params=params)
        return AgentList.from_dict(resp)
    def update(self, resource_id: str, patch: Any) -> Agent:
        data = patch.to_dict() if hasattr(patch, "to_dict") else patch
        resp = self._client._request("PATCH", f"/agents/{resource_id}", json=data)
        return Agent.from_dict(resp)

    def list_all(self, size: int = 100, **kwargs: Any) -> Iterator[Agent]:
        page = 1
        while True:
            result = self.list(ListOptions().page(page).size(size))
            yield from result.items
            if page * size >= result.total:
                break
            page += 1
