# Code generated by ambient-sdk-generator from proto — DO NOT EDIT.
# Source: /home/mturansk/projects/src/github.com/ambient/platform/platform-api-server/components/ambient-api-server/proto/ambient/v1/sessions.proto
# Proto SHA256: 62d9b56b5a74fc6d5a54e6a05010a5c03fe185f90228cf45dacbace2f8c53872
# Generated: 2026-03-10T02:34:42Z

from __future__ import annotations

import logging
import os
import ssl
from typing import Optional

import grpc

logger = logging.getLogger(__name__)

_ENV_GRPC_URL = "AMBIENT_GRPC_URL"
_ENV_TOKEN = "BOT_TOKEN"
_DEFAULT_GRPC_URL = "ambient-api-server:9000"


def _build_channel(grpc_url: str, token: str) -> grpc.Channel:
    """Build a gRPC channel. Token is attached as per-call metadata."""
    return grpc.insecure_channel(grpc_url)


class AmbientGRPCClient:
    """gRPC client for the Ambient Platform internal API.

    Intended for use inside runner Job pods where BOT_TOKEN and
    AMBIENT_GRPC_URL are injected by the operator.
    """

    def __init__(self, grpc_url: str, token: str) -> None:
        self._grpc_url = grpc_url
        self._token = token
        self._channel: Optional[grpc.Channel] = None
        self._session_messages: Optional[SessionMessagesAPI] = None

    @classmethod
    def from_env(cls) -> AmbientGRPCClient:
        """Create client from environment variables."""
        grpc_url = os.environ.get(_ENV_GRPC_URL, _DEFAULT_GRPC_URL)
        token = os.environ.get(_ENV_TOKEN, "")
        return cls(grpc_url=grpc_url, token=token)

    def _get_channel(self) -> grpc.Channel:
        if self._channel is None:
            self._channel = _build_channel(self._grpc_url, self._token)
        return self._channel

    @property
    def session_messages(self) -> SessionMessagesAPI:
        if self._session_messages is None:
            from ._session_messages_api import SessionMessagesAPI
            self._session_messages = SessionMessagesAPI(self._get_channel(), token=self._token)
        return self._session_messages

    def close(self) -> None:
        if self._channel is not None:
            self._channel.close()
            self._channel = None

    def __enter__(self) -> AmbientGRPCClient:
        return self

    def __exit__(self, *args: object) -> None:
        self.close()
