# Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
# Source: ../../ambient-api-server/openapi/openapi.yaml
# Spec SHA256: 7172ac83e56972b9e2f4812c68b759acbe06435ef304a4a897e640fb0e41e9fd
# Generated: 2026-03-19T16:56:41Z

from __future__ import annotations

from typing import Any, Callable, Iterator, TypeVar

T = TypeVar("T")


def paginate(fetch_page: Callable[..., Any], size: int = 100) -> Iterator[Any]:
    page = 1
    while True:
        result = fetch_page(page=page, size=size)
        yield from result.items
        if page * size >= result.total:
            break
        page += 1
