# Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
# Source: ../../ambient-api-server/openapi/openapi.yaml
# Spec SHA256: 7172ac83e56972b9e2f4812c68b759acbe06435ef304a4a897e640fb0e41e9fd
# Generated: 2026-03-19T16:56:41Z

from __future__ import annotations

from typing import Any, Iterator, Optional, TYPE_CHECKING

from ._base import ListOptions
from .role import Role, RoleList

if TYPE_CHECKING:
    from .client import AmbientClient


class RoleAPI:
    def __init__(self, client: AmbientClient) -> None:
        self._client = client

    def create(self, data: dict) -> Role:
        resp = self._client._request("POST", "/roles", json=data)
        return Role.from_dict(resp)

    def get(self, resource_id: str) -> Role:
        resp = self._client._request("GET", f"/roles/{resource_id}")
        return Role.from_dict(resp)

    def list(self, opts: Optional[ListOptions] = None) -> RoleList:
        params = opts.to_params() if opts else None
        resp = self._client._request("GET", "/roles", params=params)
        return RoleList.from_dict(resp)
    def update(self, resource_id: str, patch: Any) -> Role:
        data = patch.to_dict() if hasattr(patch, "to_dict") else patch
        resp = self._client._request("PATCH", f"/roles/{resource_id}", json=data)
        return Role.from_dict(resp)

    def list_all(self, size: int = 100, **kwargs: Any) -> Iterator[Role]:
        page = 1
        while True:
            result = self.list(ListOptions().page(page).size(size))
            yield from result.items
            if page * size >= result.total:
                break
            page += 1
