# Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
# Source: ../../ambient-api-server/openapi/openapi.yaml
# Spec SHA256: 7172ac83e56972b9e2f4812c68b759acbe06435ef304a4a897e640fb0e41e9fd
# Generated: 2026-03-19T16:56:41Z

from __future__ import annotations

from typing import Any, Iterator, Optional, TYPE_CHECKING

from ._base import ListOptions
from .session import Session, SessionList, SessionStatusPatch

if TYPE_CHECKING:
    from .client import AmbientClient


class SessionAPI:
    def __init__(self, client: AmbientClient) -> None:
        self._client = client

    def create(self, data: dict) -> Session:
        resp = self._client._request("POST", "/sessions", json=data)
        return Session.from_dict(resp)

    def get(self, resource_id: str) -> Session:
        resp = self._client._request("GET", f"/sessions/{resource_id}")
        return Session.from_dict(resp)

    def list(self, opts: Optional[ListOptions] = None) -> SessionList:
        params = opts.to_params() if opts else None
        resp = self._client._request("GET", "/sessions", params=params)
        return SessionList.from_dict(resp)
    def update(self, resource_id: str, patch: Any) -> Session:
        data = patch.to_dict() if hasattr(patch, "to_dict") else patch
        resp = self._client._request("PATCH", f"/sessions/{resource_id}", json=data)
        return Session.from_dict(resp)

    def delete(self, resource_id: str) -> None:
        self._client._request("DELETE", f"/sessions/{resource_id}", expect_json=False)

    def update_status(self, resource_id: str, patch: Any) -> Session:
        data = patch.to_dict() if hasattr(patch, "to_dict") else patch
        resp = self._client._request("PATCH", f"/sessions/{resource_id}/status", json=data)
        return Session.from_dict(resp)

    def start(self, resource_id: str) -> Session:
        resp = self._client._request("POST", f"/sessions/{resource_id}/start")
        return Session.from_dict(resp)

    def stop(self, resource_id: str) -> Session:
        resp = self._client._request("POST", f"/sessions/{resource_id}/stop")
        return Session.from_dict(resp)

    def list_all(self, size: int = 100, **kwargs: Any) -> Iterator[Session]:
        page = 1
        while True:
            result = self.list(ListOptions().page(page).size(size))
            yield from result.items
            if page * size >= result.total:
                break
            page += 1
