# Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
# Source: ../../ambient-api-server/openapi/openapi.yaml
# Spec SHA256: 404b5671af96841f4a876b6192afc6358b4fb8e082ca2b6da499efcf3f72c781
# Generated: 2026-03-20T16:48:23Z

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Any, Optional

from ._base import ListMeta, _parse_datetime


@dataclass(frozen=True)
class Agent:
    id: str = ""
    kind: str = ""
    href: str = ""
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    name: str = ""
    owner_user_id: str = ""
    prompt: str = ""
    version: int = 0

    @classmethod
    def from_dict(cls, data: dict) -> Agent:
        return cls(
            id=data.get("id", ""),
            kind=data.get("kind", ""),
            href=data.get("href", ""),
            created_at=_parse_datetime(data.get("created_at")),
            updated_at=_parse_datetime(data.get("updated_at")),
            name=data.get("name", ""),
            owner_user_id=data.get("owner_user_id", ""),
            prompt=data.get("prompt", ""),
            version=data.get("version", 0),
        )

    @classmethod
    def builder(cls) -> AgentBuilder:
        return AgentBuilder()


@dataclass(frozen=True)
class AgentList:
    kind: str = ""
    page: int = 0
    size: int = 0
    total: int = 0
    items: list[Agent] = ()

    @classmethod
    def from_dict(cls, data: dict) -> AgentList:
        return cls(
            kind=data.get("kind", ""),
            page=data.get("page", 0),
            size=data.get("size", 0),
            total=data.get("total", 0),
            items=[Agent.from_dict(item) for item in data.get("items", [])],
        )


class AgentBuilder:
    def __init__(self) -> None:
        self._data: dict[str, Any] = {}


    def name(self, value: str) -> AgentBuilder:
        self._data["name"] = value
        return self

    def owner_user_id(self, value: str) -> AgentBuilder:
        self._data["owner_user_id"] = value
        return self

    def prompt(self, value: str) -> AgentBuilder:
        self._data["prompt"] = value
        return self

    def build(self) -> dict:
        if "name" not in self._data:
            raise ValueError("name is required")
        if "owner_user_id" not in self._data:
            raise ValueError("owner_user_id is required")
        return dict(self._data)


class AgentPatch:
    def __init__(self) -> None:
        self._data: dict[str, Any] = {}


    def prompt(self, value: str) -> AgentPatch:
        self._data["prompt"] = value
        return self

    def to_dict(self) -> dict:
        return dict(self._data)
