# Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
# Source: ../../ambient-api-server/openapi/openapi.yaml
# Spec SHA256: 7172ac83e56972b9e2f4812c68b759acbe06435ef304a4a897e640fb0e41e9fd
# Generated: 2026-03-19T16:56:41Z

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Any, Optional

from ._base import ListMeta, _parse_datetime


@dataclass(frozen=True)
class RoleBinding:
    id: str = ""
    kind: str = ""
    href: str = ""
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    role_id: str = ""
    scope: str = ""
    scope_id: str = ""
    user_id: str = ""

    @classmethod
    def from_dict(cls, data: dict) -> RoleBinding:
        return cls(
            id=data.get("id", ""),
            kind=data.get("kind", ""),
            href=data.get("href", ""),
            created_at=_parse_datetime(data.get("created_at")),
            updated_at=_parse_datetime(data.get("updated_at")),
            role_id=data.get("role_id", ""),
            scope=data.get("scope", ""),
            scope_id=data.get("scope_id", ""),
            user_id=data.get("user_id", ""),
        )

    @classmethod
    def builder(cls) -> RoleBindingBuilder:
        return RoleBindingBuilder()


@dataclass(frozen=True)
class RoleBindingList:
    kind: str = ""
    page: int = 0
    size: int = 0
    total: int = 0
    items: list[RoleBinding] = ()

    @classmethod
    def from_dict(cls, data: dict) -> RoleBindingList:
        return cls(
            kind=data.get("kind", ""),
            page=data.get("page", 0),
            size=data.get("size", 0),
            total=data.get("total", 0),
            items=[RoleBinding.from_dict(item) for item in data.get("items", [])],
        )


class RoleBindingBuilder:
    def __init__(self) -> None:
        self._data: dict[str, Any] = {}


    def role_id(self, value: str) -> RoleBindingBuilder:
        self._data["role_id"] = value
        return self

    def scope(self, value: str) -> RoleBindingBuilder:
        self._data["scope"] = value
        return self

    def scope_id(self, value: str) -> RoleBindingBuilder:
        self._data["scope_id"] = value
        return self

    def user_id(self, value: str) -> RoleBindingBuilder:
        self._data["user_id"] = value
        return self

    def build(self) -> dict:
        if "role_id" not in self._data:
            raise ValueError("role_id is required")
        if "scope" not in self._data:
            raise ValueError("scope is required")
        if "user_id" not in self._data:
            raise ValueError("user_id is required")
        return dict(self._data)


class RoleBindingPatch:
    def __init__(self) -> None:
        self._data: dict[str, Any] = {}


    def role_id(self, value: str) -> RoleBindingPatch:
        self._data["role_id"] = value
        return self

    def scope(self, value: str) -> RoleBindingPatch:
        self._data["scope"] = value
        return self

    def scope_id(self, value: str) -> RoleBindingPatch:
        self._data["scope_id"] = value
        return self

    def user_id(self, value: str) -> RoleBindingPatch:
        self._data["user_id"] = value
        return self

    def to_dict(self) -> dict:
        return dict(self._data)
