// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ambient/v1/common.proto

package ambient_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED EventType = 0
	EventType_EVENT_TYPE_CREATED     EventType = 1
	EventType_EVENT_TYPE_UPDATED     EventType = 2
	EventType_EVENT_TYPE_DELETED     EventType = 3
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "EVENT_TYPE_CREATED",
		2: "EVENT_TYPE_UPDATED",
		3: "EVENT_TYPE_DELETED",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED": 0,
		"EVENT_TYPE_CREATED":     1,
		"EVENT_TYPE_UPDATED":     2,
		"EVENT_TYPE_DELETED":     3,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_ambient_v1_common_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_ambient_v1_common_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_ambient_v1_common_proto_rawDescGZIP(), []int{0}
}

type ObjectReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Kind          string                 `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`
	Href          string                 `protobuf:"bytes,5,opt,name=href,proto3" json:"href,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectReference) Reset() {
	*x = ObjectReference{}
	mi := &file_ambient_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectReference) ProtoMessage() {}

func (x *ObjectReference) ProtoReflect() protoreflect.Message {
	mi := &file_ambient_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectReference.ProtoReflect.Descriptor instead.
func (*ObjectReference) Descriptor() ([]byte, []int) {
	return file_ambient_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *ObjectReference) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ObjectReference) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ObjectReference) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ObjectReference) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ObjectReference) GetHref() string {
	if x != nil {
		return x.Href
	}
	return ""
}

type ListMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMeta) Reset() {
	*x = ListMeta{}
	mi := &file_ambient_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMeta) ProtoMessage() {}

func (x *ListMeta) ProtoReflect() protoreflect.Message {
	mi := &file_ambient_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMeta.ProtoReflect.Descriptor instead.
func (*ListMeta) Descriptor() ([]byte, []int) {
	return file_ambient_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *ListMeta) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListMeta) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ListMeta) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Href          string                 `protobuf:"bytes,3,opt,name=href,proto3" json:"href,omitempty"`
	Code          int32                  `protobuf:"varint,4,opt,name=code,proto3" json:"code,omitempty"`
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	OperationId   string                 `protobuf:"bytes,6,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_ambient_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_ambient_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_ambient_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *Error) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Error) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Error) GetHref() string {
	if x != nil {
		return x.Href
	}
	return ""
}

func (x *Error) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Error) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

var File_ambient_v1_common_proto protoreflect.FileDescriptor

const file_ambient_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x17ambient/v1/common.proto\x12\n" +
	"ambient.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbf\x01\n" +
	"\x0fObjectReference\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\x12\x12\n" +
	"\x04href\x18\x05 \x01(\tR\x04href\"H\n" +
	"\bListMeta\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\"\x8e\x01\n" +
	"\x05Error\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x12\n" +
	"\x04href\x18\x03 \x01(\tR\x04href\x12\x12\n" +
	"\x04code\x18\x04 \x01(\x05R\x04code\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12!\n" +
	"\foperation_id\x18\x06 \x01(\tR\voperationId*o\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12EVENT_TYPE_CREATED\x10\x01\x12\x16\n" +
	"\x12EVENT_TYPE_UPDATED\x10\x02\x12\x16\n" +
	"\x12EVENT_TYPE_DELETED\x10\x03BcZagithub.com/ambient-code/platform/components/ambient-api-server/pkg/api/grpc/ambient/v1;ambient_v1b\x06proto3"

var (
	file_ambient_v1_common_proto_rawDescOnce sync.Once
	file_ambient_v1_common_proto_rawDescData []byte
)

func file_ambient_v1_common_proto_rawDescGZIP() []byte {
	file_ambient_v1_common_proto_rawDescOnce.Do(func() {
		file_ambient_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ambient_v1_common_proto_rawDesc), len(file_ambient_v1_common_proto_rawDesc)))
	})
	return file_ambient_v1_common_proto_rawDescData
}

var file_ambient_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ambient_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ambient_v1_common_proto_goTypes = []any{
	(EventType)(0),                // 0: ambient.v1.EventType
	(*ObjectReference)(nil),       // 1: ambient.v1.ObjectReference
	(*ListMeta)(nil),              // 2: ambient.v1.ListMeta
	(*Error)(nil),                 // 3: ambient.v1.Error
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_ambient_v1_common_proto_depIdxs = []int32{
	4, // 0: ambient.v1.ObjectReference.created_at:type_name -> google.protobuf.Timestamp
	4, // 1: ambient.v1.ObjectReference.updated_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ambient_v1_common_proto_init() }
func file_ambient_v1_common_proto_init() {
	if File_ambient_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ambient_v1_common_proto_rawDesc), len(file_ambient_v1_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ambient_v1_common_proto_goTypes,
		DependencyIndexes: file_ambient_v1_common_proto_depIdxs,
		EnumInfos:         file_ambient_v1_common_proto_enumTypes,
		MessageInfos:      file_ambient_v1_common_proto_msgTypes,
	}.Build()
	File_ambient_v1_common_proto = out.File
	file_ambient_v1_common_proto_goTypes = nil
	file_ambient_v1_common_proto_depIdxs = nil
}
