// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ambient/v1/project_settings.proto

package ambient_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProjectSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *ObjectReference       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	GroupAccess   *string                `protobuf:"bytes,3,opt,name=group_access,json=groupAccess,proto3,oneof" json:"group_access,omitempty"`
	Repositories  *string                `protobuf:"bytes,5,opt,name=repositories,proto3,oneof" json:"repositories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectSettings) Reset() {
	*x = ProjectSettings{}
	mi := &file_ambient_v1_project_settings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectSettings) ProtoMessage() {}

func (x *ProjectSettings) ProtoReflect() protoreflect.Message {
	mi := &file_ambient_v1_project_settings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectSettings.ProtoReflect.Descriptor instead.
func (*ProjectSettings) Descriptor() ([]byte, []int) {
	return file_ambient_v1_project_settings_proto_rawDescGZIP(), []int{0}
}

func (x *ProjectSettings) GetMetadata() *ObjectReference {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ProjectSettings) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ProjectSettings) GetGroupAccess() string {
	if x != nil && x.GroupAccess != nil {
		return *x.GroupAccess
	}
	return ""
}

func (x *ProjectSettings) GetRepositories() string {
	if x != nil && x.Repositories != nil {
		return *x.Repositories
	}
	return ""
}

type CreateProjectSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	GroupAccess   *string                `protobuf:"bytes,2,opt,name=group_access,json=groupAccess,proto3,oneof" json:"group_access,omitempty"`
	Repositories  *string                `protobuf:"bytes,4,opt,name=repositories,proto3,oneof" json:"repositories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProjectSettingsRequest) Reset() {
	*x = CreateProjectSettingsRequest{}
	mi := &file_ambient_v1_project_settings_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProjectSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProjectSettingsRequest) ProtoMessage() {}

func (x *CreateProjectSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ambient_v1_project_settings_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProjectSettingsRequest.ProtoReflect.Descriptor instead.
func (*CreateProjectSettingsRequest) Descriptor() ([]byte, []int) {
	return file_ambient_v1_project_settings_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProjectSettingsRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CreateProjectSettingsRequest) GetGroupAccess() string {
	if x != nil && x.GroupAccess != nil {
		return *x.GroupAccess
	}
	return ""
}

func (x *CreateProjectSettingsRequest) GetRepositories() string {
	if x != nil && x.Repositories != nil {
		return *x.Repositories
	}
	return ""
}

type GetProjectSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectSettingsRequest) Reset() {
	*x = GetProjectSettingsRequest{}
	mi := &file_ambient_v1_project_settings_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectSettingsRequest) ProtoMessage() {}

func (x *GetProjectSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ambient_v1_project_settings_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectSettingsRequest.ProtoReflect.Descriptor instead.
func (*GetProjectSettingsRequest) Descriptor() ([]byte, []int) {
	return file_ambient_v1_project_settings_proto_rawDescGZIP(), []int{2}
}

func (x *GetProjectSettingsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateProjectSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId     *string                `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3,oneof" json:"project_id,omitempty"`
	GroupAccess   *string                `protobuf:"bytes,3,opt,name=group_access,json=groupAccess,proto3,oneof" json:"group_access,omitempty"`
	Repositories  *string                `protobuf:"bytes,5,opt,name=repositories,proto3,oneof" json:"repositories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProjectSettingsRequest) Reset() {
	*x = UpdateProjectSettingsRequest{}
	mi := &file_ambient_v1_project_settings_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProjectSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProjectSettingsRequest) ProtoMessage() {}

func (x *UpdateProjectSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ambient_v1_project_settings_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProjectSettingsRequest.ProtoReflect.Descriptor instead.
func (*UpdateProjectSettingsRequest) Descriptor() ([]byte, []int) {
	return file_ambient_v1_project_settings_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateProjectSettingsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateProjectSettingsRequest) GetProjectId() string {
	if x != nil && x.ProjectId != nil {
		return *x.ProjectId
	}
	return ""
}

func (x *UpdateProjectSettingsRequest) GetGroupAccess() string {
	if x != nil && x.GroupAccess != nil {
		return *x.GroupAccess
	}
	return ""
}

func (x *UpdateProjectSettingsRequest) GetRepositories() string {
	if x != nil && x.Repositories != nil {
		return *x.Repositories
	}
	return ""
}

type DeleteProjectSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProjectSettingsRequest) Reset() {
	*x = DeleteProjectSettingsRequest{}
	mi := &file_ambient_v1_project_settings_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProjectSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProjectSettingsRequest) ProtoMessage() {}

func (x *DeleteProjectSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ambient_v1_project_settings_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProjectSettingsRequest.ProtoReflect.Descriptor instead.
func (*DeleteProjectSettingsRequest) Descriptor() ([]byte, []int) {
	return file_ambient_v1_project_settings_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteProjectSettingsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListProjectSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectSettingsRequest) Reset() {
	*x = ListProjectSettingsRequest{}
	mi := &file_ambient_v1_project_settings_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectSettingsRequest) ProtoMessage() {}

func (x *ListProjectSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ambient_v1_project_settings_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectSettingsRequest.ProtoReflect.Descriptor instead.
func (*ListProjectSettingsRequest) Descriptor() ([]byte, []int) {
	return file_ambient_v1_project_settings_proto_rawDescGZIP(), []int{5}
}

func (x *ListProjectSettingsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProjectSettingsRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListProjectSettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ProjectSettings     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Metadata      *ListMeta              `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectSettingsResponse) Reset() {
	*x = ListProjectSettingsResponse{}
	mi := &file_ambient_v1_project_settings_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectSettingsResponse) ProtoMessage() {}

func (x *ListProjectSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ambient_v1_project_settings_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectSettingsResponse.ProtoReflect.Descriptor instead.
func (*ListProjectSettingsResponse) Descriptor() ([]byte, []int) {
	return file_ambient_v1_project_settings_proto_rawDescGZIP(), []int{6}
}

func (x *ListProjectSettingsResponse) GetItems() []*ProjectSettings {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListProjectSettingsResponse) GetMetadata() *ListMeta {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type DeleteProjectSettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProjectSettingsResponse) Reset() {
	*x = DeleteProjectSettingsResponse{}
	mi := &file_ambient_v1_project_settings_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProjectSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProjectSettingsResponse) ProtoMessage() {}

func (x *DeleteProjectSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ambient_v1_project_settings_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProjectSettingsResponse.ProtoReflect.Descriptor instead.
func (*DeleteProjectSettingsResponse) Descriptor() ([]byte, []int) {
	return file_ambient_v1_project_settings_proto_rawDescGZIP(), []int{7}
}

type WatchProjectSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchProjectSettingsRequest) Reset() {
	*x = WatchProjectSettingsRequest{}
	mi := &file_ambient_v1_project_settings_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchProjectSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchProjectSettingsRequest) ProtoMessage() {}

func (x *WatchProjectSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ambient_v1_project_settings_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchProjectSettingsRequest.ProtoReflect.Descriptor instead.
func (*WatchProjectSettingsRequest) Descriptor() ([]byte, []int) {
	return file_ambient_v1_project_settings_proto_rawDescGZIP(), []int{8}
}

type ProjectSettingsWatchEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Type            EventType              `protobuf:"varint,1,opt,name=type,proto3,enum=ambient.v1.EventType" json:"type,omitempty"`
	ProjectSettings *ProjectSettings       `protobuf:"bytes,2,opt,name=project_settings,json=projectSettings,proto3" json:"project_settings,omitempty"`
	ResourceId      string                 `protobuf:"bytes,3,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProjectSettingsWatchEvent) Reset() {
	*x = ProjectSettingsWatchEvent{}
	mi := &file_ambient_v1_project_settings_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectSettingsWatchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectSettingsWatchEvent) ProtoMessage() {}

func (x *ProjectSettingsWatchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_ambient_v1_project_settings_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectSettingsWatchEvent.ProtoReflect.Descriptor instead.
func (*ProjectSettingsWatchEvent) Descriptor() ([]byte, []int) {
	return file_ambient_v1_project_settings_proto_rawDescGZIP(), []int{9}
}

func (x *ProjectSettingsWatchEvent) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *ProjectSettingsWatchEvent) GetProjectSettings() *ProjectSettings {
	if x != nil {
		return x.ProjectSettings
	}
	return nil
}

func (x *ProjectSettingsWatchEvent) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

var File_ambient_v1_project_settings_proto protoreflect.FileDescriptor

const file_ambient_v1_project_settings_proto_rawDesc = "" +
	"\n" +
	"!ambient/v1/project_settings.proto\x12\n" +
	"ambient.v1\x1a\x17ambient/v1/common.proto\"\xf2\x01\n" +
	"\x0fProjectSettings\x127\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1b.ambient.v1.ObjectReferenceR\bmetadata\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12&\n" +
	"\fgroup_access\x18\x03 \x01(\tH\x00R\vgroupAccess\x88\x01\x01\x12'\n" +
	"\frepositories\x18\x05 \x01(\tH\x01R\frepositories\x88\x01\x01B\x0f\n" +
	"\r_group_accessB\x0f\n" +
	"\r_repositoriesJ\x04\b\x04\x10\x05R\x0erunner_secrets\"\xc6\x01\n" +
	"\x1cCreateProjectSettingsRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12&\n" +
	"\fgroup_access\x18\x02 \x01(\tH\x00R\vgroupAccess\x88\x01\x01\x12'\n" +
	"\frepositories\x18\x04 \x01(\tH\x01R\frepositories\x88\x01\x01B\x0f\n" +
	"\r_group_accessB\x0f\n" +
	"\r_repositoriesJ\x04\b\x03\x10\x04R\x0erunner_secrets\"+\n" +
	"\x19GetProjectSettingsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xea\x01\n" +
	"\x1cUpdateProjectSettingsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\"\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tH\x00R\tprojectId\x88\x01\x01\x12&\n" +
	"\fgroup_access\x18\x03 \x01(\tH\x01R\vgroupAccess\x88\x01\x01\x12'\n" +
	"\frepositories\x18\x05 \x01(\tH\x02R\frepositories\x88\x01\x01B\r\n" +
	"\v_project_idB\x0f\n" +
	"\r_group_accessB\x0f\n" +
	"\r_repositoriesJ\x04\b\x04\x10\x05R\x0erunner_secrets\".\n" +
	"\x1cDeleteProjectSettingsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"D\n" +
	"\x1aListProjectSettingsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\"\x82\x01\n" +
	"\x1bListProjectSettingsResponse\x121\n" +
	"\x05items\x18\x01 \x03(\v2\x1b.ambient.v1.ProjectSettingsR\x05items\x120\n" +
	"\bmetadata\x18\x02 \x01(\v2\x14.ambient.v1.ListMetaR\bmetadata\"\x1f\n" +
	"\x1dDeleteProjectSettingsResponse\"\x1d\n" +
	"\x1bWatchProjectSettingsRequest\"\xaf\x01\n" +
	"\x19ProjectSettingsWatchEvent\x12)\n" +
	"\x04type\x18\x01 \x01(\x0e2\x15.ambient.v1.EventTypeR\x04type\x12F\n" +
	"\x10project_settings\x18\x02 \x01(\v2\x1b.ambient.v1.ProjectSettingsR\x0fprojectSettings\x12\x1f\n" +
	"\vresource_id\x18\x03 \x01(\tR\n" +
	"resourceId2\xf2\x04\n" +
	"\x16ProjectSettingsService\x12X\n" +
	"\x12GetProjectSettings\x12%.ambient.v1.GetProjectSettingsRequest\x1a\x1b.ambient.v1.ProjectSettings\x12^\n" +
	"\x15CreateProjectSettings\x12(.ambient.v1.CreateProjectSettingsRequest\x1a\x1b.ambient.v1.ProjectSettings\x12^\n" +
	"\x15UpdateProjectSettings\x12(.ambient.v1.UpdateProjectSettingsRequest\x1a\x1b.ambient.v1.ProjectSettings\x12l\n" +
	"\x15DeleteProjectSettings\x12(.ambient.v1.DeleteProjectSettingsRequest\x1a).ambient.v1.DeleteProjectSettingsResponse\x12f\n" +
	"\x13ListProjectSettings\x12&.ambient.v1.ListProjectSettingsRequest\x1a'.ambient.v1.ListProjectSettingsResponse\x12h\n" +
	"\x14WatchProjectSettings\x12'.ambient.v1.WatchProjectSettingsRequest\x1a%.ambient.v1.ProjectSettingsWatchEvent0\x01BcZagithub.com/ambient-code/platform/components/ambient-api-server/pkg/api/grpc/ambient/v1;ambient_v1b\x06proto3"

var (
	file_ambient_v1_project_settings_proto_rawDescOnce sync.Once
	file_ambient_v1_project_settings_proto_rawDescData []byte
)

func file_ambient_v1_project_settings_proto_rawDescGZIP() []byte {
	file_ambient_v1_project_settings_proto_rawDescOnce.Do(func() {
		file_ambient_v1_project_settings_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ambient_v1_project_settings_proto_rawDesc), len(file_ambient_v1_project_settings_proto_rawDesc)))
	})
	return file_ambient_v1_project_settings_proto_rawDescData
}

var file_ambient_v1_project_settings_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_ambient_v1_project_settings_proto_goTypes = []any{
	(*ProjectSettings)(nil),               // 0: ambient.v1.ProjectSettings
	(*CreateProjectSettingsRequest)(nil),  // 1: ambient.v1.CreateProjectSettingsRequest
	(*GetProjectSettingsRequest)(nil),     // 2: ambient.v1.GetProjectSettingsRequest
	(*UpdateProjectSettingsRequest)(nil),  // 3: ambient.v1.UpdateProjectSettingsRequest
	(*DeleteProjectSettingsRequest)(nil),  // 4: ambient.v1.DeleteProjectSettingsRequest
	(*ListProjectSettingsRequest)(nil),    // 5: ambient.v1.ListProjectSettingsRequest
	(*ListProjectSettingsResponse)(nil),   // 6: ambient.v1.ListProjectSettingsResponse
	(*DeleteProjectSettingsResponse)(nil), // 7: ambient.v1.DeleteProjectSettingsResponse
	(*WatchProjectSettingsRequest)(nil),   // 8: ambient.v1.WatchProjectSettingsRequest
	(*ProjectSettingsWatchEvent)(nil),     // 9: ambient.v1.ProjectSettingsWatchEvent
	(*ObjectReference)(nil),               // 10: ambient.v1.ObjectReference
	(*ListMeta)(nil),                      // 11: ambient.v1.ListMeta
	(EventType)(0),                        // 12: ambient.v1.EventType
}
var file_ambient_v1_project_settings_proto_depIdxs = []int32{
	10, // 0: ambient.v1.ProjectSettings.metadata:type_name -> ambient.v1.ObjectReference
	0,  // 1: ambient.v1.ListProjectSettingsResponse.items:type_name -> ambient.v1.ProjectSettings
	11, // 2: ambient.v1.ListProjectSettingsResponse.metadata:type_name -> ambient.v1.ListMeta
	12, // 3: ambient.v1.ProjectSettingsWatchEvent.type:type_name -> ambient.v1.EventType
	0,  // 4: ambient.v1.ProjectSettingsWatchEvent.project_settings:type_name -> ambient.v1.ProjectSettings
	2,  // 5: ambient.v1.ProjectSettingsService.GetProjectSettings:input_type -> ambient.v1.GetProjectSettingsRequest
	1,  // 6: ambient.v1.ProjectSettingsService.CreateProjectSettings:input_type -> ambient.v1.CreateProjectSettingsRequest
	3,  // 7: ambient.v1.ProjectSettingsService.UpdateProjectSettings:input_type -> ambient.v1.UpdateProjectSettingsRequest
	4,  // 8: ambient.v1.ProjectSettingsService.DeleteProjectSettings:input_type -> ambient.v1.DeleteProjectSettingsRequest
	5,  // 9: ambient.v1.ProjectSettingsService.ListProjectSettings:input_type -> ambient.v1.ListProjectSettingsRequest
	8,  // 10: ambient.v1.ProjectSettingsService.WatchProjectSettings:input_type -> ambient.v1.WatchProjectSettingsRequest
	0,  // 11: ambient.v1.ProjectSettingsService.GetProjectSettings:output_type -> ambient.v1.ProjectSettings
	0,  // 12: ambient.v1.ProjectSettingsService.CreateProjectSettings:output_type -> ambient.v1.ProjectSettings
	0,  // 13: ambient.v1.ProjectSettingsService.UpdateProjectSettings:output_type -> ambient.v1.ProjectSettings
	7,  // 14: ambient.v1.ProjectSettingsService.DeleteProjectSettings:output_type -> ambient.v1.DeleteProjectSettingsResponse
	6,  // 15: ambient.v1.ProjectSettingsService.ListProjectSettings:output_type -> ambient.v1.ListProjectSettingsResponse
	9,  // 16: ambient.v1.ProjectSettingsService.WatchProjectSettings:output_type -> ambient.v1.ProjectSettingsWatchEvent
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_ambient_v1_project_settings_proto_init() }
func file_ambient_v1_project_settings_proto_init() {
	if File_ambient_v1_project_settings_proto != nil {
		return
	}
	file_ambient_v1_common_proto_init()
	file_ambient_v1_project_settings_proto_msgTypes[0].OneofWrappers = []any{}
	file_ambient_v1_project_settings_proto_msgTypes[1].OneofWrappers = []any{}
	file_ambient_v1_project_settings_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ambient_v1_project_settings_proto_rawDesc), len(file_ambient_v1_project_settings_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ambient_v1_project_settings_proto_goTypes,
		DependencyIndexes: file_ambient_v1_project_settings_proto_depIdxs,
		MessageInfos:      file_ambient_v1_project_settings_proto_msgTypes,
	}.Build()
	File_ambient_v1_project_settings_proto = out.File
	file_ambient_v1_project_settings_proto_goTypes = nil
	file_ambient_v1_project_settings_proto_depIdxs = nil
}
