// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ambient/v1/users.proto

package ambient_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *ObjectReference       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Email         *string                `protobuf:"bytes,4,opt,name=email,proto3,oneof" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_ambient_v1_users_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_ambient_v1_users_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_ambient_v1_users_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetMetadata() *ObjectReference {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         *string                `protobuf:"bytes,3,opt,name=email,proto3,oneof" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_ambient_v1_users_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ambient_v1_users_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_ambient_v1_users_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_ambient_v1_users_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ambient_v1_users_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_ambient_v1_users_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      *string                `protobuf:"bytes,2,opt,name=username,proto3,oneof" json:"username,omitempty"`
	Name          *string                `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Email         *string                `protobuf:"bytes,4,opt,name=email,proto3,oneof" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_ambient_v1_users_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ambient_v1_users_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_ambient_v1_users_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateUserRequest) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *UpdateUserRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateUserRequest) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_ambient_v1_users_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ambient_v1_users_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_ambient_v1_users_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_ambient_v1_users_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ambient_v1_users_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_ambient_v1_users_proto_rawDescGZIP(), []int{5}
}

func (x *ListUsersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUsersRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*User                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Metadata      *ListMeta              `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_ambient_v1_users_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ambient_v1_users_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_ambient_v1_users_proto_rawDescGZIP(), []int{6}
}

func (x *ListUsersResponse) GetItems() []*User {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListUsersResponse) GetMetadata() *ListMeta {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type DeleteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	mi := &file_ambient_v1_users_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ambient_v1_users_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_ambient_v1_users_proto_rawDescGZIP(), []int{7}
}

type WatchUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchUsersRequest) Reset() {
	*x = WatchUsersRequest{}
	mi := &file_ambient_v1_users_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchUsersRequest) ProtoMessage() {}

func (x *WatchUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ambient_v1_users_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchUsersRequest.ProtoReflect.Descriptor instead.
func (*WatchUsersRequest) Descriptor() ([]byte, []int) {
	return file_ambient_v1_users_proto_rawDescGZIP(), []int{8}
}

type UserWatchEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          EventType              `protobuf:"varint,1,opt,name=type,proto3,enum=ambient.v1.EventType" json:"type,omitempty"`
	User          *User                  `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	ResourceId    string                 `protobuf:"bytes,3,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserWatchEvent) Reset() {
	*x = UserWatchEvent{}
	mi := &file_ambient_v1_users_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserWatchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserWatchEvent) ProtoMessage() {}

func (x *UserWatchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_ambient_v1_users_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserWatchEvent.ProtoReflect.Descriptor instead.
func (*UserWatchEvent) Descriptor() ([]byte, []int) {
	return file_ambient_v1_users_proto_rawDescGZIP(), []int{9}
}

func (x *UserWatchEvent) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *UserWatchEvent) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UserWatchEvent) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

var File_ambient_v1_users_proto protoreflect.FileDescriptor

const file_ambient_v1_users_proto_rawDesc = "" +
	"\n" +
	"\x16ambient/v1/users.proto\x12\n" +
	"ambient.v1\x1a\x17ambient/v1/common.proto\"\x94\x01\n" +
	"\x04User\x127\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1b.ambient.v1.ObjectReferenceR\bmetadata\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x19\n" +
	"\x05email\x18\x04 \x01(\tH\x00R\x05email\x88\x01\x01B\b\n" +
	"\x06_email\"h\n" +
	"\x11CreateUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\x05email\x18\x03 \x01(\tH\x00R\x05email\x88\x01\x01B\b\n" +
	"\x06_email\" \n" +
	"\x0eGetUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x98\x01\n" +
	"\x11UpdateUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\busername\x18\x02 \x01(\tH\x00R\busername\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x01R\x04name\x88\x01\x01\x12\x19\n" +
	"\x05email\x18\x04 \x01(\tH\x02R\x05email\x88\x01\x01B\v\n" +
	"\t_usernameB\a\n" +
	"\x05_nameB\b\n" +
	"\x06_email\"#\n" +
	"\x11DeleteUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\":\n" +
	"\x10ListUsersRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\"m\n" +
	"\x11ListUsersResponse\x12&\n" +
	"\x05items\x18\x01 \x03(\v2\x10.ambient.v1.UserR\x05items\x120\n" +
	"\bmetadata\x18\x02 \x01(\v2\x14.ambient.v1.ListMetaR\bmetadata\"\x14\n" +
	"\x12DeleteUserResponse\"\x13\n" +
	"\x11WatchUsersRequest\"\x82\x01\n" +
	"\x0eUserWatchEvent\x12)\n" +
	"\x04type\x18\x01 \x01(\x0e2\x15.ambient.v1.EventTypeR\x04type\x12$\n" +
	"\x04user\x18\x02 \x01(\v2\x10.ambient.v1.UserR\x04user\x12\x1f\n" +
	"\vresource_id\x18\x03 \x01(\tR\n" +
	"resourceId2\xa6\x03\n" +
	"\vUserService\x127\n" +
	"\aGetUser\x12\x1a.ambient.v1.GetUserRequest\x1a\x10.ambient.v1.User\x12=\n" +
	"\n" +
	"CreateUser\x12\x1d.ambient.v1.CreateUserRequest\x1a\x10.ambient.v1.User\x12=\n" +
	"\n" +
	"UpdateUser\x12\x1d.ambient.v1.UpdateUserRequest\x1a\x10.ambient.v1.User\x12K\n" +
	"\n" +
	"DeleteUser\x12\x1d.ambient.v1.DeleteUserRequest\x1a\x1e.ambient.v1.DeleteUserResponse\x12H\n" +
	"\tListUsers\x12\x1c.ambient.v1.ListUsersRequest\x1a\x1d.ambient.v1.ListUsersResponse\x12I\n" +
	"\n" +
	"WatchUsers\x12\x1d.ambient.v1.WatchUsersRequest\x1a\x1a.ambient.v1.UserWatchEvent0\x01BcZagithub.com/ambient-code/platform/components/ambient-api-server/pkg/api/grpc/ambient/v1;ambient_v1b\x06proto3"

var (
	file_ambient_v1_users_proto_rawDescOnce sync.Once
	file_ambient_v1_users_proto_rawDescData []byte
)

func file_ambient_v1_users_proto_rawDescGZIP() []byte {
	file_ambient_v1_users_proto_rawDescOnce.Do(func() {
		file_ambient_v1_users_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ambient_v1_users_proto_rawDesc), len(file_ambient_v1_users_proto_rawDesc)))
	})
	return file_ambient_v1_users_proto_rawDescData
}

var file_ambient_v1_users_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_ambient_v1_users_proto_goTypes = []any{
	(*User)(nil),               // 0: ambient.v1.User
	(*CreateUserRequest)(nil),  // 1: ambient.v1.CreateUserRequest
	(*GetUserRequest)(nil),     // 2: ambient.v1.GetUserRequest
	(*UpdateUserRequest)(nil),  // 3: ambient.v1.UpdateUserRequest
	(*DeleteUserRequest)(nil),  // 4: ambient.v1.DeleteUserRequest
	(*ListUsersRequest)(nil),   // 5: ambient.v1.ListUsersRequest
	(*ListUsersResponse)(nil),  // 6: ambient.v1.ListUsersResponse
	(*DeleteUserResponse)(nil), // 7: ambient.v1.DeleteUserResponse
	(*WatchUsersRequest)(nil),  // 8: ambient.v1.WatchUsersRequest
	(*UserWatchEvent)(nil),     // 9: ambient.v1.UserWatchEvent
	(*ObjectReference)(nil),    // 10: ambient.v1.ObjectReference
	(*ListMeta)(nil),           // 11: ambient.v1.ListMeta
	(EventType)(0),             // 12: ambient.v1.EventType
}
var file_ambient_v1_users_proto_depIdxs = []int32{
	10, // 0: ambient.v1.User.metadata:type_name -> ambient.v1.ObjectReference
	0,  // 1: ambient.v1.ListUsersResponse.items:type_name -> ambient.v1.User
	11, // 2: ambient.v1.ListUsersResponse.metadata:type_name -> ambient.v1.ListMeta
	12, // 3: ambient.v1.UserWatchEvent.type:type_name -> ambient.v1.EventType
	0,  // 4: ambient.v1.UserWatchEvent.user:type_name -> ambient.v1.User
	2,  // 5: ambient.v1.UserService.GetUser:input_type -> ambient.v1.GetUserRequest
	1,  // 6: ambient.v1.UserService.CreateUser:input_type -> ambient.v1.CreateUserRequest
	3,  // 7: ambient.v1.UserService.UpdateUser:input_type -> ambient.v1.UpdateUserRequest
	4,  // 8: ambient.v1.UserService.DeleteUser:input_type -> ambient.v1.DeleteUserRequest
	5,  // 9: ambient.v1.UserService.ListUsers:input_type -> ambient.v1.ListUsersRequest
	8,  // 10: ambient.v1.UserService.WatchUsers:input_type -> ambient.v1.WatchUsersRequest
	0,  // 11: ambient.v1.UserService.GetUser:output_type -> ambient.v1.User
	0,  // 12: ambient.v1.UserService.CreateUser:output_type -> ambient.v1.User
	0,  // 13: ambient.v1.UserService.UpdateUser:output_type -> ambient.v1.User
	7,  // 14: ambient.v1.UserService.DeleteUser:output_type -> ambient.v1.DeleteUserResponse
	6,  // 15: ambient.v1.UserService.ListUsers:output_type -> ambient.v1.ListUsersResponse
	9,  // 16: ambient.v1.UserService.WatchUsers:output_type -> ambient.v1.UserWatchEvent
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_ambient_v1_users_proto_init() }
func file_ambient_v1_users_proto_init() {
	if File_ambient_v1_users_proto != nil {
		return
	}
	file_ambient_v1_common_proto_init()
	file_ambient_v1_users_proto_msgTypes[0].OneofWrappers = []any{}
	file_ambient_v1_users_proto_msgTypes[1].OneofWrappers = []any{}
	file_ambient_v1_users_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ambient_v1_users_proto_rawDesc), len(file_ambient_v1_users_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ambient_v1_users_proto_goTypes,
		DependencyIndexes: file_ambient_v1_users_proto_depIdxs,
		MessageInfos:      file_ambient_v1_users_proto_msgTypes,
	}.Build()
	File_ambient_v1_users_proto = out.File
	file_ambient_v1_users_proto_goTypes = nil
	file_ambient_v1_users_proto_depIdxs = nil
}
