apiVersion: v1
kind: ConfigMap
metadata:
  name: ambient-api-server-auth
data:
  # RSA public key for Kind/local development JWT verification (RS256, kid: FA4jixwTu0r6vvS2rfhC-mxBLO2tagx_D05POwXP_EU).
  # The corresponding private key is used to sign test JWTs in test/helper.go.
  # To regenerate: openssl genrsa -out kind-dev.pem 2048 && openssl rsa -in kind-dev.pem -pubout
  # then reformat as JWK using a tool like https://github.com/nicowillis/pem-to-jwk and update kid to match.
  jwks.json: |
    {"keys":[{"use":"sig","kty":"RSA","kid":"FA4jixwTu0r6vvS2rfhC-mxBLO2tagx_D05POwXP_EU","alg":"RS256","n":"tAPoSf8AE83mKXraK196ZNzq76kxMQDUexBA4j0LBk3ogSx-ONdexyq7bhbveQxvhBqbLbq-zvQ3cqNoewYRm-n5BoCQmhS-XMtqP8giT1vMlYz1wV87He5NL-R82lKyXQM4LYHTfhPMqZTSWJVQ_IoQ1tMJjsNhKfMORybXQufp9FR3Z0jXETpbTPgVjVBKns4VLWwIu2IamFhjapC6i-B-ZbsxB5K6HTWkdAvhWdtTbcQrJf3axYFor8eXXEWm4BdXpygsfy1FGVJwfJuTqDU07nwMdOvSrS-NHYJO5aRDwtMeNyv2g3GoXuQaD3p03kWKGQSNP7dENFrn3ygFEw","e":"AQAB"}]}
