/*
Ambient API Server

Ambient API Server

API version: 1.0.0
Contact: ambient-code@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ScheduledSessionPatchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ScheduledSessionPatchRequest{}

// ScheduledSessionPatchRequest struct for ScheduledSessionPatchRequest
type ScheduledSessionPatchRequest struct {
	Name          *string `json:"name,omitempty"`
	Description   *string `json:"description,omitempty"`
	Schedule      *string `json:"schedule,omitempty"`
	Timezone      *string `json:"timezone,omitempty"`
	Enabled       *bool   `json:"enabled,omitempty"`
	SessionPrompt *string `json:"session_prompt,omitempty"`
}

// NewScheduledSessionPatchRequest instantiates a new ScheduledSessionPatchRequest object
func NewScheduledSessionPatchRequest() *ScheduledSessionPatchRequest {
	this := ScheduledSessionPatchRequest{}
	return &this
}

// NewScheduledSessionPatchRequestWithDefaults instantiates a new ScheduledSessionPatchRequest object with defaults
func NewScheduledSessionPatchRequestWithDefaults() *ScheduledSessionPatchRequest {
	this := ScheduledSessionPatchRequest{}
	return &this
}

func (o ScheduledSessionPatchRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ScheduledSessionPatchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Schedule) {
		toSerialize["schedule"] = o.Schedule
	}
	if !IsNil(o.Timezone) {
		toSerialize["timezone"] = o.Timezone
	}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.SessionPrompt) {
		toSerialize["session_prompt"] = o.SessionPrompt
	}
	return toSerialize, nil
}

type NullableScheduledSessionPatchRequest struct {
	value *ScheduledSessionPatchRequest
	isSet bool
}

func (v NullableScheduledSessionPatchRequest) Get() *ScheduledSessionPatchRequest {
	return v.value
}

func (v *NullableScheduledSessionPatchRequest) Set(val *ScheduledSessionPatchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableScheduledSessionPatchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableScheduledSessionPatchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScheduledSessionPatchRequest(val *ScheduledSessionPatchRequest) *NullableScheduledSessionPatchRequest {
	return &NullableScheduledSessionPatchRequest{value: val, isSet: true}
}

func (v NullableScheduledSessionPatchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScheduledSessionPatchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
