/*
Ambient API Server

Ambient API Server

API version: 1.0.0
Contact: ambient-code@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AgentPatchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentPatchRequest{}

// AgentPatchRequest struct for AgentPatchRequest
type AgentPatchRequest struct {
	ProjectId            *string  `json:"project_id,omitempty"`
	ParentAgentId        *string  `json:"parent_agent_id,omitempty"`
	OwnerUserId          *string  `json:"owner_user_id,omitempty"`
	Name                 *string  `json:"name,omitempty"`
	DisplayName          *string  `json:"display_name,omitempty"`
	Description          *string  `json:"description,omitempty"`
	Prompt               *string  `json:"prompt,omitempty"`
	RepoUrl              *string  `json:"repo_url,omitempty"`
	WorkflowId           *string  `json:"workflow_id,omitempty"`
	LlmModel             *string  `json:"llm_model,omitempty"`
	LlmTemperature       *float64 `json:"llm_temperature,omitempty"`
	LlmMaxTokens         *int32   `json:"llm_max_tokens,omitempty"`
	BotAccountName       *string  `json:"bot_account_name,omitempty"`
	ResourceOverrides    *string  `json:"resource_overrides,omitempty"`
	EnvironmentVariables *string  `json:"environment_variables,omitempty"`
	Labels               *string  `json:"labels,omitempty"`
	Annotations          *string  `json:"annotations,omitempty"`
	CurrentSessionId     *string  `json:"current_session_id,omitempty"`
}

// NewAgentPatchRequest instantiates a new AgentPatchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentPatchRequest() *AgentPatchRequest {
	this := AgentPatchRequest{}
	return &this
}

// NewAgentPatchRequestWithDefaults instantiates a new AgentPatchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentPatchRequestWithDefaults() *AgentPatchRequest {
	this := AgentPatchRequest{}
	return &this
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise.
func (o *AgentPatchRequest) GetProjectId() string {
	if o == nil || IsNil(o.ProjectId) {
		var ret string
		return ret
	}
	return *o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentPatchRequest) GetProjectIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProjectId) {
		return nil, false
	}
	return o.ProjectId, true
}

// HasProjectId returns a boolean if a field has been set.
func (o *AgentPatchRequest) HasProjectId() bool {
	if o != nil && !IsNil(o.ProjectId) {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given string and assigns it to the ProjectId field.
func (o *AgentPatchRequest) SetProjectId(v string) {
	o.ProjectId = &v
}

// GetParentAgentId returns the ParentAgentId field value if set, zero value otherwise.
func (o *AgentPatchRequest) GetParentAgentId() string {
	if o == nil || IsNil(o.ParentAgentId) {
		var ret string
		return ret
	}
	return *o.ParentAgentId
}

// GetParentAgentIdOk returns a tuple with the ParentAgentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentPatchRequest) GetParentAgentIdOk() (*string, bool) {
	if o == nil || IsNil(o.ParentAgentId) {
		return nil, false
	}
	return o.ParentAgentId, true
}

// HasParentAgentId returns a boolean if a field has been set.
func (o *AgentPatchRequest) HasParentAgentId() bool {
	if o != nil && !IsNil(o.ParentAgentId) {
		return true
	}

	return false
}

// SetParentAgentId gets a reference to the given string and assigns it to the ParentAgentId field.
func (o *AgentPatchRequest) SetParentAgentId(v string) {
	o.ParentAgentId = &v
}

// GetOwnerUserId returns the OwnerUserId field value if set, zero value otherwise.
func (o *AgentPatchRequest) GetOwnerUserId() string {
	if o == nil || IsNil(o.OwnerUserId) {
		var ret string
		return ret
	}
	return *o.OwnerUserId
}

// GetOwnerUserIdOk returns a tuple with the OwnerUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentPatchRequest) GetOwnerUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.OwnerUserId) {
		return nil, false
	}
	return o.OwnerUserId, true
}

// HasOwnerUserId returns a boolean if a field has been set.
func (o *AgentPatchRequest) HasOwnerUserId() bool {
	if o != nil && !IsNil(o.OwnerUserId) {
		return true
	}

	return false
}

// SetOwnerUserId gets a reference to the given string and assigns it to the OwnerUserId field.
func (o *AgentPatchRequest) SetOwnerUserId(v string) {
	o.OwnerUserId = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *AgentPatchRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentPatchRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *AgentPatchRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *AgentPatchRequest) SetName(v string) {
	o.Name = &v
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *AgentPatchRequest) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName) {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentPatchRequest) GetDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayName) {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *AgentPatchRequest) HasDisplayName() bool {
	if o != nil && !IsNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *AgentPatchRequest) SetDisplayName(v string) {
	o.DisplayName = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *AgentPatchRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentPatchRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *AgentPatchRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *AgentPatchRequest) SetDescription(v string) {
	o.Description = &v
}

// GetPrompt returns the Prompt field value if set, zero value otherwise.
func (o *AgentPatchRequest) GetPrompt() string {
	if o == nil || IsNil(o.Prompt) {
		var ret string
		return ret
	}
	return *o.Prompt
}

// GetPromptOk returns a tuple with the Prompt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentPatchRequest) GetPromptOk() (*string, bool) {
	if o == nil || IsNil(o.Prompt) {
		return nil, false
	}
	return o.Prompt, true
}

// HasPrompt returns a boolean if a field has been set.
func (o *AgentPatchRequest) HasPrompt() bool {
	if o != nil && !IsNil(o.Prompt) {
		return true
	}

	return false
}

// SetPrompt gets a reference to the given string and assigns it to the Prompt field.
func (o *AgentPatchRequest) SetPrompt(v string) {
	o.Prompt = &v
}

// GetRepoUrl returns the RepoUrl field value if set, zero value otherwise.
func (o *AgentPatchRequest) GetRepoUrl() string {
	if o == nil || IsNil(o.RepoUrl) {
		var ret string
		return ret
	}
	return *o.RepoUrl
}

// GetRepoUrlOk returns a tuple with the RepoUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentPatchRequest) GetRepoUrlOk() (*string, bool) {
	if o == nil || IsNil(o.RepoUrl) {
		return nil, false
	}
	return o.RepoUrl, true
}

// HasRepoUrl returns a boolean if a field has been set.
func (o *AgentPatchRequest) HasRepoUrl() bool {
	if o != nil && !IsNil(o.RepoUrl) {
		return true
	}

	return false
}

// SetRepoUrl gets a reference to the given string and assigns it to the RepoUrl field.
func (o *AgentPatchRequest) SetRepoUrl(v string) {
	o.RepoUrl = &v
}

// GetWorkflowId returns the WorkflowId field value if set, zero value otherwise.
func (o *AgentPatchRequest) GetWorkflowId() string {
	if o == nil || IsNil(o.WorkflowId) {
		var ret string
		return ret
	}
	return *o.WorkflowId
}

// GetWorkflowIdOk returns a tuple with the WorkflowId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentPatchRequest) GetWorkflowIdOk() (*string, bool) {
	if o == nil || IsNil(o.WorkflowId) {
		return nil, false
	}
	return o.WorkflowId, true
}

// HasWorkflowId returns a boolean if a field has been set.
func (o *AgentPatchRequest) HasWorkflowId() bool {
	if o != nil && !IsNil(o.WorkflowId) {
		return true
	}

	return false
}

// SetWorkflowId gets a reference to the given string and assigns it to the WorkflowId field.
func (o *AgentPatchRequest) SetWorkflowId(v string) {
	o.WorkflowId = &v
}

// GetLlmModel returns the LlmModel field value if set, zero value otherwise.
func (o *AgentPatchRequest) GetLlmModel() string {
	if o == nil || IsNil(o.LlmModel) {
		var ret string
		return ret
	}
	return *o.LlmModel
}

// GetLlmModelOk returns a tuple with the LlmModel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentPatchRequest) GetLlmModelOk() (*string, bool) {
	if o == nil || IsNil(o.LlmModel) {
		return nil, false
	}
	return o.LlmModel, true
}

// HasLlmModel returns a boolean if a field has been set.
func (o *AgentPatchRequest) HasLlmModel() bool {
	if o != nil && !IsNil(o.LlmModel) {
		return true
	}

	return false
}

// SetLlmModel gets a reference to the given string and assigns it to the LlmModel field.
func (o *AgentPatchRequest) SetLlmModel(v string) {
	o.LlmModel = &v
}

// GetLlmTemperature returns the LlmTemperature field value if set, zero value otherwise.
func (o *AgentPatchRequest) GetLlmTemperature() float64 {
	if o == nil || IsNil(o.LlmTemperature) {
		var ret float64
		return ret
	}
	return *o.LlmTemperature
}

// GetLlmTemperatureOk returns a tuple with the LlmTemperature field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentPatchRequest) GetLlmTemperatureOk() (*float64, bool) {
	if o == nil || IsNil(o.LlmTemperature) {
		return nil, false
	}
	return o.LlmTemperature, true
}

// HasLlmTemperature returns a boolean if a field has been set.
func (o *AgentPatchRequest) HasLlmTemperature() bool {
	if o != nil && !IsNil(o.LlmTemperature) {
		return true
	}

	return false
}

// SetLlmTemperature gets a reference to the given float64 and assigns it to the LlmTemperature field.
func (o *AgentPatchRequest) SetLlmTemperature(v float64) {
	o.LlmTemperature = &v
}

// GetLlmMaxTokens returns the LlmMaxTokens field value if set, zero value otherwise.
func (o *AgentPatchRequest) GetLlmMaxTokens() int32 {
	if o == nil || IsNil(o.LlmMaxTokens) {
		var ret int32
		return ret
	}
	return *o.LlmMaxTokens
}

// GetLlmMaxTokensOk returns a tuple with the LlmMaxTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentPatchRequest) GetLlmMaxTokensOk() (*int32, bool) {
	if o == nil || IsNil(o.LlmMaxTokens) {
		return nil, false
	}
	return o.LlmMaxTokens, true
}

// HasLlmMaxTokens returns a boolean if a field has been set.
func (o *AgentPatchRequest) HasLlmMaxTokens() bool {
	if o != nil && !IsNil(o.LlmMaxTokens) {
		return true
	}

	return false
}

// SetLlmMaxTokens gets a reference to the given int32 and assigns it to the LlmMaxTokens field.
func (o *AgentPatchRequest) SetLlmMaxTokens(v int32) {
	o.LlmMaxTokens = &v
}

// GetBotAccountName returns the BotAccountName field value if set, zero value otherwise.
func (o *AgentPatchRequest) GetBotAccountName() string {
	if o == nil || IsNil(o.BotAccountName) {
		var ret string
		return ret
	}
	return *o.BotAccountName
}

// GetBotAccountNameOk returns a tuple with the BotAccountName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentPatchRequest) GetBotAccountNameOk() (*string, bool) {
	if o == nil || IsNil(o.BotAccountName) {
		return nil, false
	}
	return o.BotAccountName, true
}

// HasBotAccountName returns a boolean if a field has been set.
func (o *AgentPatchRequest) HasBotAccountName() bool {
	if o != nil && !IsNil(o.BotAccountName) {
		return true
	}

	return false
}

// SetBotAccountName gets a reference to the given string and assigns it to the BotAccountName field.
func (o *AgentPatchRequest) SetBotAccountName(v string) {
	o.BotAccountName = &v
}

// GetResourceOverrides returns the ResourceOverrides field value if set, zero value otherwise.
func (o *AgentPatchRequest) GetResourceOverrides() string {
	if o == nil || IsNil(o.ResourceOverrides) {
		var ret string
		return ret
	}
	return *o.ResourceOverrides
}

// GetResourceOverridesOk returns a tuple with the ResourceOverrides field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentPatchRequest) GetResourceOverridesOk() (*string, bool) {
	if o == nil || IsNil(o.ResourceOverrides) {
		return nil, false
	}
	return o.ResourceOverrides, true
}

// HasResourceOverrides returns a boolean if a field has been set.
func (o *AgentPatchRequest) HasResourceOverrides() bool {
	if o != nil && !IsNil(o.ResourceOverrides) {
		return true
	}

	return false
}

// SetResourceOverrides gets a reference to the given string and assigns it to the ResourceOverrides field.
func (o *AgentPatchRequest) SetResourceOverrides(v string) {
	o.ResourceOverrides = &v
}

// GetEnvironmentVariables returns the EnvironmentVariables field value if set, zero value otherwise.
func (o *AgentPatchRequest) GetEnvironmentVariables() string {
	if o == nil || IsNil(o.EnvironmentVariables) {
		var ret string
		return ret
	}
	return *o.EnvironmentVariables
}

// GetEnvironmentVariablesOk returns a tuple with the EnvironmentVariables field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentPatchRequest) GetEnvironmentVariablesOk() (*string, bool) {
	if o == nil || IsNil(o.EnvironmentVariables) {
		return nil, false
	}
	return o.EnvironmentVariables, true
}

// HasEnvironmentVariables returns a boolean if a field has been set.
func (o *AgentPatchRequest) HasEnvironmentVariables() bool {
	if o != nil && !IsNil(o.EnvironmentVariables) {
		return true
	}

	return false
}

// SetEnvironmentVariables gets a reference to the given string and assigns it to the EnvironmentVariables field.
func (o *AgentPatchRequest) SetEnvironmentVariables(v string) {
	o.EnvironmentVariables = &v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *AgentPatchRequest) GetLabels() string {
	if o == nil || IsNil(o.Labels) {
		var ret string
		return ret
	}
	return *o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentPatchRequest) GetLabelsOk() (*string, bool) {
	if o == nil || IsNil(o.Labels) {
		return nil, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *AgentPatchRequest) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given string and assigns it to the Labels field.
func (o *AgentPatchRequest) SetLabels(v string) {
	o.Labels = &v
}

// GetAnnotations returns the Annotations field value if set, zero value otherwise.
func (o *AgentPatchRequest) GetAnnotations() string {
	if o == nil || IsNil(o.Annotations) {
		var ret string
		return ret
	}
	return *o.Annotations
}

// GetAnnotationsOk returns a tuple with the Annotations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentPatchRequest) GetAnnotationsOk() (*string, bool) {
	if o == nil || IsNil(o.Annotations) {
		return nil, false
	}
	return o.Annotations, true
}

// HasAnnotations returns a boolean if a field has been set.
func (o *AgentPatchRequest) HasAnnotations() bool {
	if o != nil && !IsNil(o.Annotations) {
		return true
	}

	return false
}

// SetAnnotations gets a reference to the given string and assigns it to the Annotations field.
func (o *AgentPatchRequest) SetAnnotations(v string) {
	o.Annotations = &v
}

// GetCurrentSessionId returns the CurrentSessionId field value if set, zero value otherwise.
func (o *AgentPatchRequest) GetCurrentSessionId() string {
	if o == nil || IsNil(o.CurrentSessionId) {
		var ret string
		return ret
	}
	return *o.CurrentSessionId
}

// GetCurrentSessionIdOk returns a tuple with the CurrentSessionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentPatchRequest) GetCurrentSessionIdOk() (*string, bool) {
	if o == nil || IsNil(o.CurrentSessionId) {
		return nil, false
	}
	return o.CurrentSessionId, true
}

// HasCurrentSessionId returns a boolean if a field has been set.
func (o *AgentPatchRequest) HasCurrentSessionId() bool {
	if o != nil && !IsNil(o.CurrentSessionId) {
		return true
	}

	return false
}

// SetCurrentSessionId gets a reference to the given string and assigns it to the CurrentSessionId field.
func (o *AgentPatchRequest) SetCurrentSessionId(v string) {
	o.CurrentSessionId = &v
}

func (o AgentPatchRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentPatchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ProjectId) {
		toSerialize["project_id"] = o.ProjectId
	}
	if !IsNil(o.ParentAgentId) {
		toSerialize["parent_agent_id"] = o.ParentAgentId
	}
	if !IsNil(o.OwnerUserId) {
		toSerialize["owner_user_id"] = o.OwnerUserId
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.DisplayName) {
		toSerialize["display_name"] = o.DisplayName
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Prompt) {
		toSerialize["prompt"] = o.Prompt
	}
	if !IsNil(o.RepoUrl) {
		toSerialize["repo_url"] = o.RepoUrl
	}
	if !IsNil(o.WorkflowId) {
		toSerialize["workflow_id"] = o.WorkflowId
	}
	if !IsNil(o.LlmModel) {
		toSerialize["llm_model"] = o.LlmModel
	}
	if !IsNil(o.LlmTemperature) {
		toSerialize["llm_temperature"] = o.LlmTemperature
	}
	if !IsNil(o.LlmMaxTokens) {
		toSerialize["llm_max_tokens"] = o.LlmMaxTokens
	}
	if !IsNil(o.BotAccountName) {
		toSerialize["bot_account_name"] = o.BotAccountName
	}
	if !IsNil(o.ResourceOverrides) {
		toSerialize["resource_overrides"] = o.ResourceOverrides
	}
	if !IsNil(o.EnvironmentVariables) {
		toSerialize["environment_variables"] = o.EnvironmentVariables
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	if !IsNil(o.Annotations) {
		toSerialize["annotations"] = o.Annotations
	}
	if !IsNil(o.CurrentSessionId) {
		toSerialize["current_session_id"] = o.CurrentSessionId
	}
	return toSerialize, nil
}

type NullableAgentPatchRequest struct {
	value *AgentPatchRequest
	isSet bool
}

func (v NullableAgentPatchRequest) Get() *AgentPatchRequest {
	return v.value
}

func (v *NullableAgentPatchRequest) Set(val *AgentPatchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentPatchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentPatchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentPatchRequest(val *AgentPatchRequest) *NullableAgentPatchRequest {
	return &NullableAgentPatchRequest{value: val, isSet: true}
}

func (v NullableAgentPatchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentPatchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
