/*
Ambient API Server

Ambient API Server

API version: 1.0.0
Contact: ambient-code@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the ScheduledSession type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ScheduledSession{}

// ScheduledSession struct for ScheduledSession
type ScheduledSession struct {
	Id            *string    `json:"id,omitempty"`
	Kind          *string    `json:"kind,omitempty"`
	Href          *string    `json:"href,omitempty"`
	CreatedAt     *time.Time `json:"created_at,omitempty"`
	UpdatedAt     *time.Time `json:"updated_at,omitempty"`
	Name          string     `json:"name"`
	Description   *string    `json:"description,omitempty"`
	ProjectId     string     `json:"project_id"`
	AgentId       string     `json:"agent_id"`
	Schedule      string     `json:"schedule"`
	Timezone      *string    `json:"timezone,omitempty"`
	Enabled       *bool      `json:"enabled,omitempty"`
	SessionPrompt *string    `json:"session_prompt,omitempty"`
	LastRunAt     *time.Time `json:"last_run_at,omitempty"`
	NextRunAt     *time.Time `json:"next_run_at,omitempty"`
}

// NewScheduledSession instantiates a new ScheduledSession object
func NewScheduledSession(name string, projectId string, agentId string, schedule string) *ScheduledSession {
	this := ScheduledSession{}
	this.Name = name
	this.ProjectId = projectId
	this.AgentId = agentId
	this.Schedule = schedule
	return &this
}

// NewScheduledSessionWithDefaults instantiates a new ScheduledSession object with defaults
func NewScheduledSessionWithDefaults() *ScheduledSession {
	this := ScheduledSession{}
	return &this
}

func (o ScheduledSession) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ScheduledSession) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Kind) {
		toSerialize["kind"] = o.Kind
	}
	if !IsNil(o.Href) {
		toSerialize["href"] = o.Href
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["project_id"] = o.ProjectId
	toSerialize["agent_id"] = o.AgentId
	toSerialize["schedule"] = o.Schedule
	if !IsNil(o.Timezone) {
		toSerialize["timezone"] = o.Timezone
	}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.SessionPrompt) {
		toSerialize["session_prompt"] = o.SessionPrompt
	}
	if !IsNil(o.LastRunAt) {
		toSerialize["last_run_at"] = o.LastRunAt
	}
	if !IsNil(o.NextRunAt) {
		toSerialize["next_run_at"] = o.NextRunAt
	}
	return toSerialize, nil
}

type NullableScheduledSession struct {
	value *ScheduledSession
	isSet bool
}

func (v NullableScheduledSession) Get() *ScheduledSession {
	return v.value
}

func (v *NullableScheduledSession) Set(val *ScheduledSession) {
	v.value = val
	v.isSet = true
}

func (v NullableScheduledSession) IsSet() bool {
	return v.isSet
}

func (v *NullableScheduledSession) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScheduledSession(val *ScheduledSession) *NullableScheduledSession {
	return &NullableScheduledSession{value: val, isSet: true}
}

func (v NullableScheduledSession) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScheduledSession) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
