/*
Ambient API Server

Ambient API Server

API version: 1.0.0
Contact: ambient-code@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SessionMessagePushRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SessionMessagePushRequest{}

// SessionMessagePushRequest struct for SessionMessagePushRequest
type SessionMessagePushRequest struct {
	// Event type tag. Defaults to `user` if omitted.
	EventType *string `json:"event_type,omitempty"`
	// Message body
	Payload *string `json:"payload,omitempty"`
}

// NewSessionMessagePushRequest instantiates a new SessionMessagePushRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSessionMessagePushRequest() *SessionMessagePushRequest {
	this := SessionMessagePushRequest{}
	var eventType string = "user"
	this.EventType = &eventType
	return &this
}

// NewSessionMessagePushRequestWithDefaults instantiates a new SessionMessagePushRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSessionMessagePushRequestWithDefaults() *SessionMessagePushRequest {
	this := SessionMessagePushRequest{}
	var eventType string = "user"
	this.EventType = &eventType
	return &this
}

// GetEventType returns the EventType field value if set, zero value otherwise.
func (o *SessionMessagePushRequest) GetEventType() string {
	if o == nil || IsNil(o.EventType) {
		var ret string
		return ret
	}
	return *o.EventType
}

// GetEventTypeOk returns a tuple with the EventType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionMessagePushRequest) GetEventTypeOk() (*string, bool) {
	if o == nil || IsNil(o.EventType) {
		return nil, false
	}
	return o.EventType, true
}

// HasEventType returns a boolean if a field has been set.
func (o *SessionMessagePushRequest) HasEventType() bool {
	if o != nil && !IsNil(o.EventType) {
		return true
	}

	return false
}

// SetEventType gets a reference to the given string and assigns it to the EventType field.
func (o *SessionMessagePushRequest) SetEventType(v string) {
	o.EventType = &v
}

// GetPayload returns the Payload field value if set, zero value otherwise.
func (o *SessionMessagePushRequest) GetPayload() string {
	if o == nil || IsNil(o.Payload) {
		var ret string
		return ret
	}
	return *o.Payload
}

// GetPayloadOk returns a tuple with the Payload field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionMessagePushRequest) GetPayloadOk() (*string, bool) {
	if o == nil || IsNil(o.Payload) {
		return nil, false
	}
	return o.Payload, true
}

// HasPayload returns a boolean if a field has been set.
func (o *SessionMessagePushRequest) HasPayload() bool {
	if o != nil && !IsNil(o.Payload) {
		return true
	}

	return false
}

// SetPayload gets a reference to the given string and assigns it to the Payload field.
func (o *SessionMessagePushRequest) SetPayload(v string) {
	o.Payload = &v
}

func (o SessionMessagePushRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SessionMessagePushRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EventType) {
		toSerialize["event_type"] = o.EventType
	}
	if !IsNil(o.Payload) {
		toSerialize["payload"] = o.Payload
	}
	return toSerialize, nil
}

type NullableSessionMessagePushRequest struct {
	value *SessionMessagePushRequest
	isSet bool
}

func (v NullableSessionMessagePushRequest) Get() *SessionMessagePushRequest {
	return v.value
}

func (v *NullableSessionMessagePushRequest) Set(val *SessionMessagePushRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSessionMessagePushRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSessionMessagePushRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSessionMessagePushRequest(val *SessionMessagePushRequest) *NullableSessionMessagePushRequest {
	return &NullableSessionMessagePushRequest{value: val, isSet: true}
}

func (v NullableSessionMessagePushRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSessionMessagePushRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
