/*
Ambient API Server

Ambient API Server

API version: 1.0.0
Contact: ambient-code@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ScheduledSessionList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ScheduledSessionList{}

// ScheduledSessionList struct for ScheduledSessionList
type ScheduledSessionList struct {
	Kind  string              `json:"kind"`
	Page  int32               `json:"page"`
	Size  int32               `json:"size"`
	Total int32               `json:"total"`
	Items []ScheduledSession  `json:"items"`
}

type _ScheduledSessionList ScheduledSessionList

// NewScheduledSessionList instantiates a new ScheduledSessionList object
func NewScheduledSessionList(kind string, page int32, size int32, total int32, items []ScheduledSession) *ScheduledSessionList {
	this := ScheduledSessionList{}
	this.Kind = kind
	this.Page = page
	this.Size = size
	this.Total = total
	this.Items = items
	return &this
}

// NewScheduledSessionListWithDefaults instantiates a new ScheduledSessionList object with defaults
func NewScheduledSessionListWithDefaults() *ScheduledSessionList {
	this := ScheduledSessionList{}
	return &this
}

func (o ScheduledSessionList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ScheduledSessionList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["kind"] = o.Kind
	toSerialize["page"] = o.Page
	toSerialize["size"] = o.Size
	toSerialize["total"] = o.Total
	toSerialize["items"] = o.Items
	return toSerialize, nil
}

func (o *ScheduledSessionList) UnmarshalJSON(data []byte) (err error) {
	requiredProperties := []string{
		"kind",
		"page",
		"size",
		"total",
		"items",
	}

	allProperties := make(map[string]interface{})
	err = json.Unmarshal(data, &allProperties)
	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varScheduledSessionList := _ScheduledSessionList{}
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varScheduledSessionList)
	if err != nil {
		return err
	}

	*o = ScheduledSessionList(varScheduledSessionList)
	return err
}

type NullableScheduledSessionList struct {
	value *ScheduledSessionList
	isSet bool
}

func (v NullableScheduledSessionList) Get() *ScheduledSessionList {
	return v.value
}

func (v *NullableScheduledSessionList) Set(val *ScheduledSessionList) {
	v.value = val
	v.isSet = true
}

func (v NullableScheduledSessionList) IsSet() bool {
	return v.isSet
}

func (v *NullableScheduledSessionList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScheduledSessionList(val *ScheduledSessionList) *NullableScheduledSessionList {
	return &NullableScheduledSessionList{value: val, isSet: true}
}

func (v NullableScheduledSessionList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScheduledSessionList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
