/*
Ambient API Server

Ambient API Server

API version: 1.0.0
Contact: ambient-code@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the Agent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Agent{}

// Agent struct for Agent
type Agent struct {
	Id                   *string    `json:"id,omitempty"`
	Kind                 *string    `json:"kind,omitempty"`
	Href                 *string    `json:"href,omitempty"`
	CreatedAt            *time.Time `json:"created_at,omitempty"`
	UpdatedAt            *time.Time `json:"updated_at,omitempty"`
	ProjectId            string     `json:"project_id"`
	ParentAgentId        *string    `json:"parent_agent_id,omitempty"`
	OwnerUserId          string     `json:"owner_user_id"`
	Name                 string     `json:"name"`
	DisplayName          *string    `json:"display_name,omitempty"`
	Description          *string    `json:"description,omitempty"`
	Prompt               *string    `json:"prompt,omitempty"`
	RepoUrl              *string    `json:"repo_url,omitempty"`
	WorkflowId           *string    `json:"workflow_id,omitempty"`
	LlmModel             *string    `json:"llm_model,omitempty"`
	LlmTemperature       *float64   `json:"llm_temperature,omitempty"`
	LlmMaxTokens         *int32     `json:"llm_max_tokens,omitempty"`
	BotAccountName       *string    `json:"bot_account_name,omitempty"`
	ResourceOverrides    *string    `json:"resource_overrides,omitempty"`
	EnvironmentVariables *string    `json:"environment_variables,omitempty"`
	Labels               *string    `json:"labels,omitempty"`
	Annotations          *string    `json:"annotations,omitempty"`
	CurrentSessionId     *string    `json:"current_session_id,omitempty"`
}

type _Agent Agent

// NewAgent instantiates a new Agent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgent(projectId string, ownerUserId string, name string) *Agent {
	this := Agent{}
	this.ProjectId = projectId
	this.OwnerUserId = ownerUserId
	this.Name = name
	return &this
}

// NewAgentWithDefaults instantiates a new Agent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentWithDefaults() *Agent {
	this := Agent{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Agent) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Agent) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Agent) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Agent) SetId(v string) {
	o.Id = &v
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *Agent) GetKind() string {
	if o == nil || IsNil(o.Kind) {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Agent) GetKindOk() (*string, bool) {
	if o == nil || IsNil(o.Kind) {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *Agent) HasKind() bool {
	if o != nil && !IsNil(o.Kind) {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *Agent) SetKind(v string) {
	o.Kind = &v
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *Agent) GetHref() string {
	if o == nil || IsNil(o.Href) {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Agent) GetHrefOk() (*string, bool) {
	if o == nil || IsNil(o.Href) {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *Agent) HasHref() bool {
	if o != nil && !IsNil(o.Href) {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *Agent) SetHref(v string) {
	o.Href = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *Agent) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Agent) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *Agent) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *Agent) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *Agent) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Agent) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *Agent) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *Agent) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetProjectId returns the ProjectId field value
func (o *Agent) GetProjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *Agent) GetProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *Agent) SetProjectId(v string) {
	o.ProjectId = v
}

// GetParentAgentId returns the ParentAgentId field value if set, zero value otherwise.
func (o *Agent) GetParentAgentId() string {
	if o == nil || IsNil(o.ParentAgentId) {
		var ret string
		return ret
	}
	return *o.ParentAgentId
}

// GetParentAgentIdOk returns a tuple with the ParentAgentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Agent) GetParentAgentIdOk() (*string, bool) {
	if o == nil || IsNil(o.ParentAgentId) {
		return nil, false
	}
	return o.ParentAgentId, true
}

// HasParentAgentId returns a boolean if a field has been set.
func (o *Agent) HasParentAgentId() bool {
	if o != nil && !IsNil(o.ParentAgentId) {
		return true
	}

	return false
}

// SetParentAgentId gets a reference to the given string and assigns it to the ParentAgentId field.
func (o *Agent) SetParentAgentId(v string) {
	o.ParentAgentId = &v
}

// GetOwnerUserId returns the OwnerUserId field value
func (o *Agent) GetOwnerUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OwnerUserId
}

// GetOwnerUserIdOk returns a tuple with the OwnerUserId field value
// and a boolean to check if the value has been set.
func (o *Agent) GetOwnerUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OwnerUserId, true
}

// SetOwnerUserId sets field value
func (o *Agent) SetOwnerUserId(v string) {
	o.OwnerUserId = v
}

// GetName returns the Name field value
func (o *Agent) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Agent) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Agent) SetName(v string) {
	o.Name = v
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *Agent) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName) {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Agent) GetDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayName) {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *Agent) HasDisplayName() bool {
	if o != nil && !IsNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *Agent) SetDisplayName(v string) {
	o.DisplayName = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *Agent) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Agent) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *Agent) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *Agent) SetDescription(v string) {
	o.Description = &v
}

// GetPrompt returns the Prompt field value if set, zero value otherwise.
func (o *Agent) GetPrompt() string {
	if o == nil || IsNil(o.Prompt) {
		var ret string
		return ret
	}
	return *o.Prompt
}

// GetPromptOk returns a tuple with the Prompt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Agent) GetPromptOk() (*string, bool) {
	if o == nil || IsNil(o.Prompt) {
		return nil, false
	}
	return o.Prompt, true
}

// HasPrompt returns a boolean if a field has been set.
func (o *Agent) HasPrompt() bool {
	if o != nil && !IsNil(o.Prompt) {
		return true
	}

	return false
}

// SetPrompt gets a reference to the given string and assigns it to the Prompt field.
func (o *Agent) SetPrompt(v string) {
	o.Prompt = &v
}

// GetRepoUrl returns the RepoUrl field value if set, zero value otherwise.
func (o *Agent) GetRepoUrl() string {
	if o == nil || IsNil(o.RepoUrl) {
		var ret string
		return ret
	}
	return *o.RepoUrl
}

// GetRepoUrlOk returns a tuple with the RepoUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Agent) GetRepoUrlOk() (*string, bool) {
	if o == nil || IsNil(o.RepoUrl) {
		return nil, false
	}
	return o.RepoUrl, true
}

// HasRepoUrl returns a boolean if a field has been set.
func (o *Agent) HasRepoUrl() bool {
	if o != nil && !IsNil(o.RepoUrl) {
		return true
	}

	return false
}

// SetRepoUrl gets a reference to the given string and assigns it to the RepoUrl field.
func (o *Agent) SetRepoUrl(v string) {
	o.RepoUrl = &v
}

// GetWorkflowId returns the WorkflowId field value if set, zero value otherwise.
func (o *Agent) GetWorkflowId() string {
	if o == nil || IsNil(o.WorkflowId) {
		var ret string
		return ret
	}
	return *o.WorkflowId
}

// GetWorkflowIdOk returns a tuple with the WorkflowId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Agent) GetWorkflowIdOk() (*string, bool) {
	if o == nil || IsNil(o.WorkflowId) {
		return nil, false
	}
	return o.WorkflowId, true
}

// HasWorkflowId returns a boolean if a field has been set.
func (o *Agent) HasWorkflowId() bool {
	if o != nil && !IsNil(o.WorkflowId) {
		return true
	}

	return false
}

// SetWorkflowId gets a reference to the given string and assigns it to the WorkflowId field.
func (o *Agent) SetWorkflowId(v string) {
	o.WorkflowId = &v
}

// GetLlmModel returns the LlmModel field value if set, zero value otherwise.
func (o *Agent) GetLlmModel() string {
	if o == nil || IsNil(o.LlmModel) {
		var ret string
		return ret
	}
	return *o.LlmModel
}

// GetLlmModelOk returns a tuple with the LlmModel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Agent) GetLlmModelOk() (*string, bool) {
	if o == nil || IsNil(o.LlmModel) {
		return nil, false
	}
	return o.LlmModel, true
}

// HasLlmModel returns a boolean if a field has been set.
func (o *Agent) HasLlmModel() bool {
	if o != nil && !IsNil(o.LlmModel) {
		return true
	}

	return false
}

// SetLlmModel gets a reference to the given string and assigns it to the LlmModel field.
func (o *Agent) SetLlmModel(v string) {
	o.LlmModel = &v
}

// GetLlmTemperature returns the LlmTemperature field value if set, zero value otherwise.
func (o *Agent) GetLlmTemperature() float64 {
	if o == nil || IsNil(o.LlmTemperature) {
		var ret float64
		return ret
	}
	return *o.LlmTemperature
}

// GetLlmTemperatureOk returns a tuple with the LlmTemperature field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Agent) GetLlmTemperatureOk() (*float64, bool) {
	if o == nil || IsNil(o.LlmTemperature) {
		return nil, false
	}
	return o.LlmTemperature, true
}

// HasLlmTemperature returns a boolean if a field has been set.
func (o *Agent) HasLlmTemperature() bool {
	if o != nil && !IsNil(o.LlmTemperature) {
		return true
	}

	return false
}

// SetLlmTemperature gets a reference to the given float64 and assigns it to the LlmTemperature field.
func (o *Agent) SetLlmTemperature(v float64) {
	o.LlmTemperature = &v
}

// GetLlmMaxTokens returns the LlmMaxTokens field value if set, zero value otherwise.
func (o *Agent) GetLlmMaxTokens() int32 {
	if o == nil || IsNil(o.LlmMaxTokens) {
		var ret int32
		return ret
	}
	return *o.LlmMaxTokens
}

// GetLlmMaxTokensOk returns a tuple with the LlmMaxTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Agent) GetLlmMaxTokensOk() (*int32, bool) {
	if o == nil || IsNil(o.LlmMaxTokens) {
		return nil, false
	}
	return o.LlmMaxTokens, true
}

// HasLlmMaxTokens returns a boolean if a field has been set.
func (o *Agent) HasLlmMaxTokens() bool {
	if o != nil && !IsNil(o.LlmMaxTokens) {
		return true
	}

	return false
}

// SetLlmMaxTokens gets a reference to the given int32 and assigns it to the LlmMaxTokens field.
func (o *Agent) SetLlmMaxTokens(v int32) {
	o.LlmMaxTokens = &v
}

// GetBotAccountName returns the BotAccountName field value if set, zero value otherwise.
func (o *Agent) GetBotAccountName() string {
	if o == nil || IsNil(o.BotAccountName) {
		var ret string
		return ret
	}
	return *o.BotAccountName
}

// GetBotAccountNameOk returns a tuple with the BotAccountName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Agent) GetBotAccountNameOk() (*string, bool) {
	if o == nil || IsNil(o.BotAccountName) {
		return nil, false
	}
	return o.BotAccountName, true
}

// HasBotAccountName returns a boolean if a field has been set.
func (o *Agent) HasBotAccountName() bool {
	if o != nil && !IsNil(o.BotAccountName) {
		return true
	}

	return false
}

// SetBotAccountName gets a reference to the given string and assigns it to the BotAccountName field.
func (o *Agent) SetBotAccountName(v string) {
	o.BotAccountName = &v
}

// GetResourceOverrides returns the ResourceOverrides field value if set, zero value otherwise.
func (o *Agent) GetResourceOverrides() string {
	if o == nil || IsNil(o.ResourceOverrides) {
		var ret string
		return ret
	}
	return *o.ResourceOverrides
}

// GetResourceOverridesOk returns a tuple with the ResourceOverrides field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Agent) GetResourceOverridesOk() (*string, bool) {
	if o == nil || IsNil(o.ResourceOverrides) {
		return nil, false
	}
	return o.ResourceOverrides, true
}

// HasResourceOverrides returns a boolean if a field has been set.
func (o *Agent) HasResourceOverrides() bool {
	if o != nil && !IsNil(o.ResourceOverrides) {
		return true
	}

	return false
}

// SetResourceOverrides gets a reference to the given string and assigns it to the ResourceOverrides field.
func (o *Agent) SetResourceOverrides(v string) {
	o.ResourceOverrides = &v
}

// GetEnvironmentVariables returns the EnvironmentVariables field value if set, zero value otherwise.
func (o *Agent) GetEnvironmentVariables() string {
	if o == nil || IsNil(o.EnvironmentVariables) {
		var ret string
		return ret
	}
	return *o.EnvironmentVariables
}

// GetEnvironmentVariablesOk returns a tuple with the EnvironmentVariables field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Agent) GetEnvironmentVariablesOk() (*string, bool) {
	if o == nil || IsNil(o.EnvironmentVariables) {
		return nil, false
	}
	return o.EnvironmentVariables, true
}

// HasEnvironmentVariables returns a boolean if a field has been set.
func (o *Agent) HasEnvironmentVariables() bool {
	if o != nil && !IsNil(o.EnvironmentVariables) {
		return true
	}

	return false
}

// SetEnvironmentVariables gets a reference to the given string and assigns it to the EnvironmentVariables field.
func (o *Agent) SetEnvironmentVariables(v string) {
	o.EnvironmentVariables = &v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *Agent) GetLabels() string {
	if o == nil || IsNil(o.Labels) {
		var ret string
		return ret
	}
	return *o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Agent) GetLabelsOk() (*string, bool) {
	if o == nil || IsNil(o.Labels) {
		return nil, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *Agent) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given string and assigns it to the Labels field.
func (o *Agent) SetLabels(v string) {
	o.Labels = &v
}

// GetAnnotations returns the Annotations field value if set, zero value otherwise.
func (o *Agent) GetAnnotations() string {
	if o == nil || IsNil(o.Annotations) {
		var ret string
		return ret
	}
	return *o.Annotations
}

// GetAnnotationsOk returns a tuple with the Annotations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Agent) GetAnnotationsOk() (*string, bool) {
	if o == nil || IsNil(o.Annotations) {
		return nil, false
	}
	return o.Annotations, true
}

// HasAnnotations returns a boolean if a field has been set.
func (o *Agent) HasAnnotations() bool {
	if o != nil && !IsNil(o.Annotations) {
		return true
	}

	return false
}

// SetAnnotations gets a reference to the given string and assigns it to the Annotations field.
func (o *Agent) SetAnnotations(v string) {
	o.Annotations = &v
}

// GetCurrentSessionId returns the CurrentSessionId field value if set, zero value otherwise.
func (o *Agent) GetCurrentSessionId() string {
	if o == nil || IsNil(o.CurrentSessionId) {
		var ret string
		return ret
	}
	return *o.CurrentSessionId
}

// GetCurrentSessionIdOk returns a tuple with the CurrentSessionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Agent) GetCurrentSessionIdOk() (*string, bool) {
	if o == nil || IsNil(o.CurrentSessionId) {
		return nil, false
	}
	return o.CurrentSessionId, true
}

// HasCurrentSessionId returns a boolean if a field has been set.
func (o *Agent) HasCurrentSessionId() bool {
	if o != nil && !IsNil(o.CurrentSessionId) {
		return true
	}

	return false
}

// SetCurrentSessionId gets a reference to the given string and assigns it to the CurrentSessionId field.
func (o *Agent) SetCurrentSessionId(v string) {
	o.CurrentSessionId = &v
}

func (o Agent) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Agent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Kind) {
		toSerialize["kind"] = o.Kind
	}
	if !IsNil(o.Href) {
		toSerialize["href"] = o.Href
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	toSerialize["project_id"] = o.ProjectId
	if !IsNil(o.ParentAgentId) {
		toSerialize["parent_agent_id"] = o.ParentAgentId
	}
	toSerialize["owner_user_id"] = o.OwnerUserId
	toSerialize["name"] = o.Name
	if !IsNil(o.DisplayName) {
		toSerialize["display_name"] = o.DisplayName
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Prompt) {
		toSerialize["prompt"] = o.Prompt
	}
	if !IsNil(o.RepoUrl) {
		toSerialize["repo_url"] = o.RepoUrl
	}
	if !IsNil(o.WorkflowId) {
		toSerialize["workflow_id"] = o.WorkflowId
	}
	if !IsNil(o.LlmModel) {
		toSerialize["llm_model"] = o.LlmModel
	}
	if !IsNil(o.LlmTemperature) {
		toSerialize["llm_temperature"] = o.LlmTemperature
	}
	if !IsNil(o.LlmMaxTokens) {
		toSerialize["llm_max_tokens"] = o.LlmMaxTokens
	}
	if !IsNil(o.BotAccountName) {
		toSerialize["bot_account_name"] = o.BotAccountName
	}
	if !IsNil(o.ResourceOverrides) {
		toSerialize["resource_overrides"] = o.ResourceOverrides
	}
	if !IsNil(o.EnvironmentVariables) {
		toSerialize["environment_variables"] = o.EnvironmentVariables
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	if !IsNil(o.Annotations) {
		toSerialize["annotations"] = o.Annotations
	}
	if !IsNil(o.CurrentSessionId) {
		toSerialize["current_session_id"] = o.CurrentSessionId
	}
	return toSerialize, nil
}

func (o *Agent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"project_id",
		"owner_user_id",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAgent := _Agent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAgent)

	if err != nil {
		return err
	}

	*o = Agent(varAgent)

	return err
}

type NullableAgent struct {
	value *Agent
	isSet bool
}

func (v NullableAgent) Get() *Agent {
	return v.value
}

func (v *NullableAgent) Set(val *Agent) {
	v.value = val
	v.isSet = true
}

func (v NullableAgent) IsSet() bool {
	return v.isSet
}

func (v *NullableAgent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgent(val *Agent) *NullableAgent {
	return &NullableAgent{value: val, isSet: true}
}

func (v NullableAgent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
