/*
Ambient API Server

Ambient API Server

API version: 1.0.0
Contact: ambient-code@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the RoleBindingPatchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RoleBindingPatchRequest{}

// RoleBindingPatchRequest struct for RoleBindingPatchRequest
type RoleBindingPatchRequest struct {
	UserId  *string `json:"user_id,omitempty"`
	RoleId  *string `json:"role_id,omitempty"`
	Scope   *string `json:"scope,omitempty"`
	ScopeId *string `json:"scope_id,omitempty"`
}

// NewRoleBindingPatchRequest instantiates a new RoleBindingPatchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRoleBindingPatchRequest() *RoleBindingPatchRequest {
	this := RoleBindingPatchRequest{}
	return &this
}

// NewRoleBindingPatchRequestWithDefaults instantiates a new RoleBindingPatchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRoleBindingPatchRequestWithDefaults() *RoleBindingPatchRequest {
	this := RoleBindingPatchRequest{}
	return &this
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *RoleBindingPatchRequest) GetUserId() string {
	if o == nil || IsNil(o.UserId) {
		var ret string
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoleBindingPatchRequest) GetUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.UserId) {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *RoleBindingPatchRequest) HasUserId() bool {
	if o != nil && !IsNil(o.UserId) {
		return true
	}

	return false
}

// SetUserId gets a reference to the given string and assigns it to the UserId field.
func (o *RoleBindingPatchRequest) SetUserId(v string) {
	o.UserId = &v
}

// GetRoleId returns the RoleId field value if set, zero value otherwise.
func (o *RoleBindingPatchRequest) GetRoleId() string {
	if o == nil || IsNil(o.RoleId) {
		var ret string
		return ret
	}
	return *o.RoleId
}

// GetRoleIdOk returns a tuple with the RoleId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoleBindingPatchRequest) GetRoleIdOk() (*string, bool) {
	if o == nil || IsNil(o.RoleId) {
		return nil, false
	}
	return o.RoleId, true
}

// HasRoleId returns a boolean if a field has been set.
func (o *RoleBindingPatchRequest) HasRoleId() bool {
	if o != nil && !IsNil(o.RoleId) {
		return true
	}

	return false
}

// SetRoleId gets a reference to the given string and assigns it to the RoleId field.
func (o *RoleBindingPatchRequest) SetRoleId(v string) {
	o.RoleId = &v
}

// GetScope returns the Scope field value if set, zero value otherwise.
func (o *RoleBindingPatchRequest) GetScope() string {
	if o == nil || IsNil(o.Scope) {
		var ret string
		return ret
	}
	return *o.Scope
}

// GetScopeOk returns a tuple with the Scope field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoleBindingPatchRequest) GetScopeOk() (*string, bool) {
	if o == nil || IsNil(o.Scope) {
		return nil, false
	}
	return o.Scope, true
}

// HasScope returns a boolean if a field has been set.
func (o *RoleBindingPatchRequest) HasScope() bool {
	if o != nil && !IsNil(o.Scope) {
		return true
	}

	return false
}

// SetScope gets a reference to the given string and assigns it to the Scope field.
func (o *RoleBindingPatchRequest) SetScope(v string) {
	o.Scope = &v
}

// GetScopeId returns the ScopeId field value if set, zero value otherwise.
func (o *RoleBindingPatchRequest) GetScopeId() string {
	if o == nil || IsNil(o.ScopeId) {
		var ret string
		return ret
	}
	return *o.ScopeId
}

// GetScopeIdOk returns a tuple with the ScopeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoleBindingPatchRequest) GetScopeIdOk() (*string, bool) {
	if o == nil || IsNil(o.ScopeId) {
		return nil, false
	}
	return o.ScopeId, true
}

// HasScopeId returns a boolean if a field has been set.
func (o *RoleBindingPatchRequest) HasScopeId() bool {
	if o != nil && !IsNil(o.ScopeId) {
		return true
	}

	return false
}

// SetScopeId gets a reference to the given string and assigns it to the ScopeId field.
func (o *RoleBindingPatchRequest) SetScopeId(v string) {
	o.ScopeId = &v
}

func (o RoleBindingPatchRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RoleBindingPatchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.UserId) {
		toSerialize["user_id"] = o.UserId
	}
	if !IsNil(o.RoleId) {
		toSerialize["role_id"] = o.RoleId
	}
	if !IsNil(o.Scope) {
		toSerialize["scope"] = o.Scope
	}
	if !IsNil(o.ScopeId) {
		toSerialize["scope_id"] = o.ScopeId
	}
	return toSerialize, nil
}

type NullableRoleBindingPatchRequest struct {
	value *RoleBindingPatchRequest
	isSet bool
}

func (v NullableRoleBindingPatchRequest) Get() *RoleBindingPatchRequest {
	return v.value
}

func (v *NullableRoleBindingPatchRequest) Set(val *RoleBindingPatchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRoleBindingPatchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRoleBindingPatchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRoleBindingPatchRequest(val *RoleBindingPatchRequest) *NullableRoleBindingPatchRequest {
	return &NullableRoleBindingPatchRequest{value: val, isSet: true}
}

func (v NullableRoleBindingPatchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRoleBindingPatchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
