/*
Ambient API Server

Ambient API Server

API version: 1.0.0
Contact: ambient-code@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiAmbientV1ProjectsIdScheduledSessionsSsIdTriggerPost200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiAmbientV1ProjectsIdScheduledSessionsSsIdTriggerPost200Response{}

// ApiAmbientV1ProjectsIdScheduledSessionsSsIdTriggerPost200Response struct for ApiAmbientV1ProjectsIdScheduledSessionsSsIdTriggerPost200Response
type ApiAmbientV1ProjectsIdScheduledSessionsSsIdTriggerPost200Response struct {
	Status *string `json:"status,omitempty"`
}

// NewApiAmbientV1ProjectsIdScheduledSessionsSsIdTriggerPost200Response instantiates a new ApiAmbientV1ProjectsIdScheduledSessionsSsIdTriggerPost200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiAmbientV1ProjectsIdScheduledSessionsSsIdTriggerPost200Response() *ApiAmbientV1ProjectsIdScheduledSessionsSsIdTriggerPost200Response {
	this := ApiAmbientV1ProjectsIdScheduledSessionsSsIdTriggerPost200Response{}
	return &this
}

// NewApiAmbientV1ProjectsIdScheduledSessionsSsIdTriggerPost200ResponseWithDefaults instantiates a new ApiAmbientV1ProjectsIdScheduledSessionsSsIdTriggerPost200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiAmbientV1ProjectsIdScheduledSessionsSsIdTriggerPost200ResponseWithDefaults() *ApiAmbientV1ProjectsIdScheduledSessionsSsIdTriggerPost200Response {
	this := ApiAmbientV1ProjectsIdScheduledSessionsSsIdTriggerPost200Response{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ApiAmbientV1ProjectsIdScheduledSessionsSsIdTriggerPost200Response) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAmbientV1ProjectsIdScheduledSessionsSsIdTriggerPost200Response) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ApiAmbientV1ProjectsIdScheduledSessionsSsIdTriggerPost200Response) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *ApiAmbientV1ProjectsIdScheduledSessionsSsIdTriggerPost200Response) SetStatus(v string) {
	o.Status = &v
}

func (o ApiAmbientV1ProjectsIdScheduledSessionsSsIdTriggerPost200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiAmbientV1ProjectsIdScheduledSessionsSsIdTriggerPost200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableApiAmbientV1ProjectsIdScheduledSessionsSsIdTriggerPost200Response struct {
	value *ApiAmbientV1ProjectsIdScheduledSessionsSsIdTriggerPost200Response
	isSet bool
}

func (v NullableApiAmbientV1ProjectsIdScheduledSessionsSsIdTriggerPost200Response) Get() *ApiAmbientV1ProjectsIdScheduledSessionsSsIdTriggerPost200Response {
	return v.value
}

func (v *NullableApiAmbientV1ProjectsIdScheduledSessionsSsIdTriggerPost200Response) Set(val *ApiAmbientV1ProjectsIdScheduledSessionsSsIdTriggerPost200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiAmbientV1ProjectsIdScheduledSessionsSsIdTriggerPost200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiAmbientV1ProjectsIdScheduledSessionsSsIdTriggerPost200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiAmbientV1ProjectsIdScheduledSessionsSsIdTriggerPost200Response(val *ApiAmbientV1ProjectsIdScheduledSessionsSsIdTriggerPost200Response) *NullableApiAmbientV1ProjectsIdScheduledSessionsSsIdTriggerPost200Response {
	return &NullableApiAmbientV1ProjectsIdScheduledSessionsSsIdTriggerPost200Response{value: val, isSet: true}
}

func (v NullableApiAmbientV1ProjectsIdScheduledSessionsSsIdTriggerPost200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiAmbientV1ProjectsIdScheduledSessionsSsIdTriggerPost200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
