/*
Ambient API Server

Ambient API Server

API version: 1.0.0
Contact: ambient-code@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AgentPatchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentPatchRequest{}

// AgentPatchRequest struct for AgentPatchRequest
type AgentPatchRequest struct {
	Name        *string `json:"name,omitempty"`
	DisplayName *string `json:"display_name,omitempty"`
	Description *string `json:"description,omitempty"`
	// Update agent prompt (access controlled by RBAC)
	Prompt         *string  `json:"prompt,omitempty"`
	RepoUrl        *string  `json:"repo_url,omitempty"`
	LlmModel       *string  `json:"llm_model,omitempty"`
	LlmTemperature *float64 `json:"llm_temperature,omitempty"`
	LlmMaxTokens   *int32   `json:"llm_max_tokens,omitempty"`
	Labels         *string  `json:"labels,omitempty"`
	Annotations    *string  `json:"annotations,omitempty"`
}

// NewAgentPatchRequest instantiates a new AgentPatchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentPatchRequest() *AgentPatchRequest {
	this := AgentPatchRequest{}
	return &this
}

// NewAgentPatchRequestWithDefaults instantiates a new AgentPatchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentPatchRequestWithDefaults() *AgentPatchRequest {
	this := AgentPatchRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *AgentPatchRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentPatchRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *AgentPatchRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *AgentPatchRequest) SetName(v string) {
	o.Name = &v
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *AgentPatchRequest) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName) {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentPatchRequest) GetDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayName) {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *AgentPatchRequest) HasDisplayName() bool {
	if o != nil && !IsNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *AgentPatchRequest) SetDisplayName(v string) {
	o.DisplayName = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *AgentPatchRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentPatchRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *AgentPatchRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *AgentPatchRequest) SetDescription(v string) {
	o.Description = &v
}

// GetPrompt returns the Prompt field value if set, zero value otherwise.
func (o *AgentPatchRequest) GetPrompt() string {
	if o == nil || IsNil(o.Prompt) {
		var ret string
		return ret
	}
	return *o.Prompt
}

// GetPromptOk returns a tuple with the Prompt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentPatchRequest) GetPromptOk() (*string, bool) {
	if o == nil || IsNil(o.Prompt) {
		return nil, false
	}
	return o.Prompt, true
}

// HasPrompt returns a boolean if a field has been set.
func (o *AgentPatchRequest) HasPrompt() bool {
	if o != nil && !IsNil(o.Prompt) {
		return true
	}

	return false
}

// SetPrompt gets a reference to the given string and assigns it to the Prompt field.
func (o *AgentPatchRequest) SetPrompt(v string) {
	o.Prompt = &v
}

// GetRepoUrl returns the RepoUrl field value if set, zero value otherwise.
func (o *AgentPatchRequest) GetRepoUrl() string {
	if o == nil || IsNil(o.RepoUrl) {
		var ret string
		return ret
	}
	return *o.RepoUrl
}

// GetRepoUrlOk returns a tuple with the RepoUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentPatchRequest) GetRepoUrlOk() (*string, bool) {
	if o == nil || IsNil(o.RepoUrl) {
		return nil, false
	}
	return o.RepoUrl, true
}

// HasRepoUrl returns a boolean if a field has been set.
func (o *AgentPatchRequest) HasRepoUrl() bool {
	if o != nil && !IsNil(o.RepoUrl) {
		return true
	}

	return false
}

// SetRepoUrl gets a reference to the given string and assigns it to the RepoUrl field.
func (o *AgentPatchRequest) SetRepoUrl(v string) {
	o.RepoUrl = &v
}

// GetLlmModel returns the LlmModel field value if set, zero value otherwise.
func (o *AgentPatchRequest) GetLlmModel() string {
	if o == nil || IsNil(o.LlmModel) {
		var ret string
		return ret
	}
	return *o.LlmModel
}

// GetLlmModelOk returns a tuple with the LlmModel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentPatchRequest) GetLlmModelOk() (*string, bool) {
	if o == nil || IsNil(o.LlmModel) {
		return nil, false
	}
	return o.LlmModel, true
}

// HasLlmModel returns a boolean if a field has been set.
func (o *AgentPatchRequest) HasLlmModel() bool {
	if o != nil && !IsNil(o.LlmModel) {
		return true
	}

	return false
}

// SetLlmModel gets a reference to the given string and assigns it to the LlmModel field.
func (o *AgentPatchRequest) SetLlmModel(v string) {
	o.LlmModel = &v
}

// GetLlmTemperature returns the LlmTemperature field value if set, zero value otherwise.
func (o *AgentPatchRequest) GetLlmTemperature() float64 {
	if o == nil || IsNil(o.LlmTemperature) {
		var ret float64
		return ret
	}
	return *o.LlmTemperature
}

// GetLlmTemperatureOk returns a tuple with the LlmTemperature field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentPatchRequest) GetLlmTemperatureOk() (*float64, bool) {
	if o == nil || IsNil(o.LlmTemperature) {
		return nil, false
	}
	return o.LlmTemperature, true
}

// HasLlmTemperature returns a boolean if a field has been set.
func (o *AgentPatchRequest) HasLlmTemperature() bool {
	if o != nil && !IsNil(o.LlmTemperature) {
		return true
	}

	return false
}

// SetLlmTemperature gets a reference to the given float64 and assigns it to the LlmTemperature field.
func (o *AgentPatchRequest) SetLlmTemperature(v float64) {
	o.LlmTemperature = &v
}

// GetLlmMaxTokens returns the LlmMaxTokens field value if set, zero value otherwise.
func (o *AgentPatchRequest) GetLlmMaxTokens() int32 {
	if o == nil || IsNil(o.LlmMaxTokens) {
		var ret int32
		return ret
	}
	return *o.LlmMaxTokens
}

// GetLlmMaxTokensOk returns a tuple with the LlmMaxTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentPatchRequest) GetLlmMaxTokensOk() (*int32, bool) {
	if o == nil || IsNil(o.LlmMaxTokens) {
		return nil, false
	}
	return o.LlmMaxTokens, true
}

// HasLlmMaxTokens returns a boolean if a field has been set.
func (o *AgentPatchRequest) HasLlmMaxTokens() bool {
	if o != nil && !IsNil(o.LlmMaxTokens) {
		return true
	}

	return false
}

// SetLlmMaxTokens gets a reference to the given int32 and assigns it to the LlmMaxTokens field.
func (o *AgentPatchRequest) SetLlmMaxTokens(v int32) {
	o.LlmMaxTokens = &v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *AgentPatchRequest) GetLabels() string {
	if o == nil || IsNil(o.Labels) {
		var ret string
		return ret
	}
	return *o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentPatchRequest) GetLabelsOk() (*string, bool) {
	if o == nil || IsNil(o.Labels) {
		return nil, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *AgentPatchRequest) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given string and assigns it to the Labels field.
func (o *AgentPatchRequest) SetLabels(v string) {
	o.Labels = &v
}

// GetAnnotations returns the Annotations field value if set, zero value otherwise.
func (o *AgentPatchRequest) GetAnnotations() string {
	if o == nil || IsNil(o.Annotations) {
		var ret string
		return ret
	}
	return *o.Annotations
}

// GetAnnotationsOk returns a tuple with the Annotations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentPatchRequest) GetAnnotationsOk() (*string, bool) {
	if o == nil || IsNil(o.Annotations) {
		return nil, false
	}
	return o.Annotations, true
}

// HasAnnotations returns a boolean if a field has been set.
func (o *AgentPatchRequest) HasAnnotations() bool {
	if o != nil && !IsNil(o.Annotations) {
		return true
	}

	return false
}

// SetAnnotations gets a reference to the given string and assigns it to the Annotations field.
func (o *AgentPatchRequest) SetAnnotations(v string) {
	o.Annotations = &v
}

func (o AgentPatchRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentPatchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.DisplayName) {
		toSerialize["display_name"] = o.DisplayName
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Prompt) {
		toSerialize["prompt"] = o.Prompt
	}
	if !IsNil(o.RepoUrl) {
		toSerialize["repo_url"] = o.RepoUrl
	}
	if !IsNil(o.LlmModel) {
		toSerialize["llm_model"] = o.LlmModel
	}
	if !IsNil(o.LlmTemperature) {
		toSerialize["llm_temperature"] = o.LlmTemperature
	}
	if !IsNil(o.LlmMaxTokens) {
		toSerialize["llm_max_tokens"] = o.LlmMaxTokens
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	if !IsNil(o.Annotations) {
		toSerialize["annotations"] = o.Annotations
	}
	return toSerialize, nil
}

type NullableAgentPatchRequest struct {
	value *AgentPatchRequest
	isSet bool
}

func (v NullableAgentPatchRequest) Get() *AgentPatchRequest {
	return v.value
}

func (v *NullableAgentPatchRequest) Set(val *AgentPatchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentPatchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentPatchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentPatchRequest(val *AgentPatchRequest) *NullableAgentPatchRequest {
	return &NullableAgentPatchRequest{value: val, isSet: true}
}

func (v NullableAgentPatchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentPatchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
