#!/bin/bash
# rebase-main-to-alpha.sh - Rebase all commits from main into the alpha branch.
#
# Creates a working branch off alpha, replays all commits from main that are
# not yet in alpha, and opens a PR against alpha for human review and merge.
# Merge conflicts are left in-place with conflict markers for the reviewer.
#
# Usage:
#   ./scripts/rebase-main-to-alpha.sh
#
# Requirements:
#   - git, gh (GitHub CLI)
#   - Authenticated to GitHub: gh auth status
#   - Remote named 'upstream' pointing to ambient-code/platform

set -euo pipefail

UPSTREAM="${UPSTREAM:-upstream}"
MAIN_BRANCH="main"
ALPHA_BRANCH="alpha"
TIMESTAMP="$(date +%Y%m%d-%H%M%S)"
WORK_BRANCH="chore/rebase-main-to-alpha-${TIMESTAMP}"

log() { echo "[rebase-main-to-alpha] $*"; }
die() { echo "[rebase-main-to-alpha] ERROR: $*" >&2; exit 1; }

# Verify required tools
command -v git >/dev/null || die "git not found"
command -v gh  >/dev/null || die "gh (GitHub CLI) not found — install from https://cli.github.com"

# Verify upstream remote exists
git remote get-url "${UPSTREAM}" >/dev/null 2>&1 || \
  die "Remote '${UPSTREAM}' not found. Add it: git remote add upstream git@github.com:ambient-code/platform.git"

log "Fetching ${UPSTREAM}..."
git fetch "${UPSTREAM}" "${MAIN_BRANCH}" "${ALPHA_BRANCH}"

MAIN_SHA="$(git rev-parse "${UPSTREAM}/${MAIN_BRANCH}")"
ALPHA_SHA="$(git rev-parse "${UPSTREAM}/${ALPHA_BRANCH}")"
MERGE_BASE="$(git merge-base "${ALPHA_SHA}" "${MAIN_SHA}")"

log "upstream/${MAIN_BRANCH}:  ${MAIN_SHA}"
log "upstream/${ALPHA_BRANCH}: ${ALPHA_SHA}"
log "merge-base:               ${MERGE_BASE}"

# Count commits in main not yet in alpha
COMMIT_COUNT="$(git rev-list --count "${ALPHA_SHA}..${MAIN_SHA}")"
if [ "${COMMIT_COUNT}" -eq 0 ]; then
  log "alpha is already up to date with main. Nothing to do."
  exit 0
fi
log "Commits in main not in alpha: ${COMMIT_COUNT}"

# Create work branch off alpha
log "Creating work branch '${WORK_BRANCH}' from ${UPSTREAM}/${ALPHA_BRANCH}..."
git checkout -b "${WORK_BRANCH}" "${UPSTREAM}/${ALPHA_BRANCH}"

# Attempt rebase of main onto the work branch (best-effort)
log "Rebasing ${UPSTREAM}/${MAIN_BRANCH} onto ${WORK_BRANCH} (best-effort)..."
REBASE_EXIT=0
git rebase --onto "${WORK_BRANCH}" "${MERGE_BASE}" "${UPSTREAM}/${MAIN_BRANCH}" || REBASE_EXIT=$?

if [ "${REBASE_EXIT}" -ne 0 ]; then
  log "Rebase encountered conflicts. Collecting conflict state..."

  # Stage all files — conflict markers will be preserved in working tree
  git add -A || true

  CONFLICT_FILES="$(git diff --name-only --diff-filter=U HEAD 2>/dev/null || git status --short | grep '^UU' | awk '{print $2}' || echo "(see git status)")"

  # Abort the rebase so we're on a clean branch, then merge instead as fallback
  git rebase --abort 2>/dev/null || true

  log "Rebase aborted due to conflicts. Falling back to merge for best-effort commit..."
  git merge --no-ff --allow-unrelated-histories "${UPSTREAM}/${MAIN_BRANCH}" \
    -m "chore: merge main into alpha (best-effort — conflicts require human resolution)

Automated merge of upstream/main into upstream/alpha.
Conflicts detected during rebase; falling back to merge.

Conflicting files:
${CONFLICT_FILES}

Please resolve conflicts and merge this PR manually.
Generated by scripts/rebase-main-to-alpha.sh on ${TIMESTAMP}." || {
    # Merge also has conflicts — stage everything and commit with markers
    git add -A
    git commit --no-verify -m "chore: best-effort merge main into alpha (conflicts present)

Automated merge of upstream/main into upstream/alpha.
Both rebase and merge encountered conflicts. Conflict markers are
present in the files listed below. A human must resolve these before
merging this PR.

Generated by scripts/rebase-main-to-alpha.sh on ${TIMESTAMP}."
  }
else
  log "Rebase completed cleanly."
  # Rebase leaves us in detached-ish state — need to update work branch
  git checkout -B "${WORK_BRANCH}"
fi

# Push work branch
log "Pushing ${WORK_BRANCH} to ${UPSTREAM}..."
git push "${UPSTREAM}" "${WORK_BRANCH}" --force-with-lease

# Open PR against alpha
log "Opening PR against ${ALPHA_BRANCH}..."
PR_URL="$(gh pr create \
  --repo ambient-code/platform \
  --base "${ALPHA_BRANCH}" \
  --head "${WORK_BRANCH}" \
  --title "chore: rebase main into alpha (${TIMESTAMP})" \
  --body "$(cat <<EOF
## Summary

Automated best-effort rebase of \`main\` into \`alpha\`.

- Commits from \`main\` not yet in \`alpha\`: **${COMMIT_COUNT}**
- merge-base: \`${MERGE_BASE}\`
- Generated: ${TIMESTAMP}

## Review Instructions

1. Check for conflict markers (\`<<<<<<<\`) in changed files.
2. Resolve any conflicts and push to this branch.
3. Verify the build passes.
4. Merge into \`alpha\`.

If there are no conflicts, this PR can be merged directly.

Generated by \`scripts/rebase-main-to-alpha.sh\`.
EOF
)")"

log "PR opened: ${PR_URL}"
log "Done. A human should review and merge: ${PR_URL}"
