// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 404b5671af96841f4a876b6192afc6358b4fb8e082ca2b6da499efcf3f72c781
// Generated: 2026-03-20T16:48:23Z

import type { AmbientClientConfig, ListOptions, RequestOptions, ListMeta } from './base';
import { ambientFetch, buildQueryString } from './base';
import type { Agent, AgentList, AgentCreateRequest, AgentPatchRequest } from './agent';
import type { Session } from './session';

export type AgentSessionList = ListMeta & { items: Session[] };

export type StartRequest = {
  prompt?: string;
};

export type StartResponse = {
  session?: Session;
  starting_prompt?: string;
};

export class AgentAPI {
  constructor(private readonly config: AmbientClientConfig) {}

  async create(data: AgentCreateRequest, opts?: RequestOptions): Promise<Agent> {
    return ambientFetch<Agent>(this.config, 'POST', '/agents', data, opts);
  }

  async get(id: string, opts?: RequestOptions): Promise<Agent> {
    return ambientFetch<Agent>(this.config, 'GET', `/agents/${id}`, undefined, opts);
  }

  async list(listOpts?: ListOptions, opts?: RequestOptions): Promise<AgentList> {
    const qs = buildQueryString(listOpts);
    return ambientFetch<AgentList>(this.config, 'GET', `/agents${qs}`, undefined, opts);
  }

  async update(id: string, patch: AgentPatchRequest, opts?: RequestOptions): Promise<Agent> {
    return ambientFetch<Agent>(this.config, 'PATCH', `/agents/${id}`, patch, opts);
  }

  async *listAll(size: number = 100, opts?: RequestOptions): AsyncGenerator<Agent> {
    let page = 1;
    while (true) {
      const result = await this.list({ page, size }, opts);
      for (const item of result.items) {
        yield item;
      }
      if (page * size >= result.total) {
        break;
      }
      page++;
    }
  }

  async listByProject(projectId: string, listOpts?: ListOptions, opts?: RequestOptions): Promise<AgentList> {
    const qs = buildQueryString(listOpts);
    return ambientFetch<AgentList>(this.config, 'GET', `/projects/${encodeURIComponent(projectId)}/agents${qs}`, undefined, opts);
  }

  async getByProject(projectId: string, agentId: string, opts?: RequestOptions): Promise<Agent> {
    return ambientFetch<Agent>(this.config, 'GET', `/projects/${encodeURIComponent(projectId)}/agents/${encodeURIComponent(agentId)}`, undefined, opts);
  }

  async createInProject(projectId: string, data: AgentCreateRequest, opts?: RequestOptions): Promise<Agent> {
    return ambientFetch<Agent>(this.config, 'POST', `/projects/${encodeURIComponent(projectId)}/agents`, data, opts);
  }

  async updateInProject(projectId: string, agentId: string, patch: AgentPatchRequest, opts?: RequestOptions): Promise<Agent> {
    return ambientFetch<Agent>(this.config, 'PATCH', `/projects/${encodeURIComponent(projectId)}/agents/${encodeURIComponent(agentId)}`, patch, opts);
  }

  async deleteInProject(projectId: string, agentId: string, opts?: RequestOptions): Promise<void> {
    return ambientFetch<void>(this.config, 'DELETE', `/projects/${encodeURIComponent(projectId)}/agents/${encodeURIComponent(agentId)}`, undefined, opts);
  }

  async start(projectId: string, agentId: string, prompt?: string, opts?: RequestOptions): Promise<StartResponse> {
    return ambientFetch<StartResponse>(this.config, 'POST', `/projects/${encodeURIComponent(projectId)}/agents/${encodeURIComponent(agentId)}/start`, { prompt }, opts);
  }

  async getStartPreview(projectId: string, agentId: string, opts?: RequestOptions): Promise<StartResponse> {
    return ambientFetch<StartResponse>(this.config, 'GET', `/projects/${encodeURIComponent(projectId)}/agents/${encodeURIComponent(agentId)}/start`, undefined, opts);
  }

  async sessions(projectId: string, agentId: string, listOpts?: ListOptions, opts?: RequestOptions): Promise<AgentSessionList> {
    const qs = buildQueryString(listOpts);
    return ambientFetch<AgentSessionList>(this.config, 'GET', `/projects/${encodeURIComponent(projectId)}/agents/${encodeURIComponent(agentId)}/sessions${qs}`, undefined, opts);
  }
}
