// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 404b5671af96841f4a876b6192afc6358b4fb8e082ca2b6da499efcf3f72c781
// Generated: 2026-03-20T16:48:23Z

import type { ObjectReference, ListMeta } from './base';

export type Agent = ObjectReference & {
  annotations?: string;
  current_session_id?: string;
  labels?: string;
  name: string;
  owner_user_id?: string;
  project_id?: string;
  prompt?: string;
  version?: number;
};

export type AgentList = ListMeta & {
  items: Agent[];
};

export type AgentCreateRequest = {
  annotations?: string;
  labels?: string;
  name: string;
  owner_user_id?: string;
  project_id?: string;
  prompt?: string;
};

export type AgentPatchRequest = {
  annotations?: string;
  labels?: string;
  name?: string;
  prompt?: string;
};

export class AgentBuilder {
  private data: Record<string, unknown> = {};

  annotations(value: string): this {
    this.data['annotations'] = value;
    return this;
  }

  labels(value: string): this {
    this.data['labels'] = value;
    return this;
  }

  name(value: string): this {
    this.data['name'] = value;
    return this;
  }

  ownerUserId(value: string): this {
    this.data['owner_user_id'] = value;
    return this;
  }

  projectId(value: string): this {
    this.data['project_id'] = value;
    return this;
  }

  prompt(value: string): this {
    this.data['prompt'] = value;
    return this;
  }

  build(): AgentCreateRequest {
    if (!this.data['name']) {
      throw new Error('name is required');
    }
    return this.data as AgentCreateRequest;
  }
}

export class AgentPatchBuilder {
  private data: Record<string, unknown> = {};

  annotations(value: string): this {
    this.data['annotations'] = value;
    return this;
  }

  labels(value: string): this {
    this.data['labels'] = value;
    return this;
  }

  name(value: string): this {
    this.data['name'] = value;
    return this;
  }

  prompt(value: string): this {
    this.data['prompt'] = value;
    return this;
  }

  build(): AgentPatchRequest {
    return this.data as AgentPatchRequest;
  }
}
