// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 7172ac83e56972b9e2f4812c68b759acbe06435ef304a4a897e640fb0e41e9fd
// Generated: 2026-03-19T16:56:41Z

import type { ObjectReference, ListMeta } from './base';

export type SessionMessage = ObjectReference & {
  event_type: string;
  payload: string;
  seq: number;
  session_id: string;
};

export type SessionMessageList = ListMeta & {
  items: SessionMessage[];
};

export type SessionMessageCreateRequest = {
  event_type?: string;
  payload?: string;
};

export type SessionMessagePatchRequest = {
};

export class SessionMessageBuilder {
  private data: Record<string, unknown> = {};


  eventType(value: string): this {
    this.data['event_type'] = value;
    return this;
  }

  payload(value: string): this {
    this.data['payload'] = value;
    return this;
  }

  build(): SessionMessageCreateRequest {
    return this.data as SessionMessageCreateRequest;
  }
}

export class SessionMessagePatchBuilder {
  private data: Record<string, unknown> = {};


  build(): SessionMessagePatchRequest {
    return this.data as SessionMessagePatchRequest;
  }
}
