// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 7172ac83e56972b9e2f4812c68b759acbe06435ef304a4a897e640fb0e41e9fd
// Generated: 2026-03-19T16:56:41Z

package client

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"

	"github.com/ambient-code/platform/components/ambient-sdk/go-sdk/types"
)

type SessionMessageAPI struct {
	client *Client
}

func (c *Client) SessionMessages() *SessionMessageAPI {
	return &SessionMessageAPI{client: c}
}

func (a *SessionMessageAPI) Create(ctx context.Context, resource *types.SessionMessage) (*types.SessionMessage, error) {
	body, err := json.Marshal(resource)
	if err != nil {
		return nil, fmt.Errorf("marshal session_message: %w", err)
	}
	var result types.SessionMessage
	if err := a.client.do(ctx, http.MethodPost, "/sessions", body, http.StatusCreated, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *SessionMessageAPI) Get(ctx context.Context, id string) (*types.SessionMessage, error) {
	var result types.SessionMessage
	if err := a.client.do(ctx, http.MethodGet, "/sessions/"+url.PathEscape(id), nil, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *SessionMessageAPI) List(ctx context.Context, opts *types.ListOptions) (*types.SessionMessageList, error) {
	var result types.SessionMessageList
	if err := a.client.doWithQuery(ctx, http.MethodGet, "/sessions", nil, http.StatusOK, &result, opts); err != nil {
		return nil, err
	}
	return &result, nil
}
func (a *SessionMessageAPI) ListAll(ctx context.Context, opts *types.ListOptions) *Iterator[types.SessionMessage] {
	return NewIterator(func(page int) (*types.SessionMessageList, error) {
		o := *opts
		o.Page = page
		return a.List(ctx, &o)
	})
}
